# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alerm.ui'
#
# Created: Mon Sep 11 15:26:35 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_alerm(object):
    def setupUi(self, alerm):
        alerm.setObjectName("alerm")
        alerm.resize(255, 339)
        self.verticalLayout_2 = QtGui.QVBoxLayout(alerm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtGui.QWidget(alerm)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtGui.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.name_lbl = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_lbl.sizePolicy().hasHeightForWidth())
        self.name_lbl.setSizePolicy(sizePolicy)
        self.name_lbl.setText("")
        self.name_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.name_lbl.setObjectName("name_lbl")
        self.gridLayout.addWidget(self.name_lbl, 0, 0, 1, 1)
        self.phone_lbl = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_lbl.sizePolicy().hasHeightForWidth())
        self.phone_lbl.setSizePolicy(sizePolicy)
        self.phone_lbl.setText("")
        self.phone_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.phone_lbl.setObjectName("phone_lbl")
        self.gridLayout.addWidget(self.phone_lbl, 3, 0, 1, 1)
        self.barcode_lbl = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barcode_lbl.sizePolicy().hasHeightForWidth())
        self.barcode_lbl.setSizePolicy(sizePolicy)
        self.barcode_lbl.setText("")
        self.barcode_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.barcode_lbl.setObjectName("barcode_lbl")
        self.gridLayout.addWidget(self.barcode_lbl, 4, 0, 1, 1)
        self.label = QtGui.QLabel(self.widget_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.widget_3 = QtGui.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_4 = QtGui.QWidget(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ok_bun = QtGui.QPushButton(self.widget_4)
        self.ok_bun.setObjectName("ok_bun")
        self.horizontalLayout_2.addWidget(self.ok_bun)
        self.cancel = QtGui.QPushButton(self.widget_4)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.gridLayout_2.addWidget(self.widget_4, 7, 0, 1, 2)
        self.gp_lbl = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gp_lbl.sizePolicy().hasHeightForWidth())
        self.gp_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gp_lbl.setFont(font)
        self.gp_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.gp_lbl.setObjectName("gp_lbl")
        self.gridLayout_2.addWidget(self.gp_lbl, 2, 0, 1, 2)
        self.tottal_lbl = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tottal_lbl.sizePolicy().hasHeightForWidth())
        self.tottal_lbl.setSizePolicy(sizePolicy)
        self.tottal_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.tottal_lbl.setObjectName("tottal_lbl")
        self.gridLayout_2.addWidget(self.tottal_lbl, 4, 0, 1, 1)
        self.gp_type = QtGui.QLabel(self.widget_3)
        self.gp_type.setText("")
        self.gp_type.setAlignment(QtCore.Qt.AlignCenter)
        self.gp_type.setObjectName("gp_type")
        self.gridLayout_2.addWidget(self.gp_type, 0, 0, 1, 1)
        self.raist = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.raist.setFont(font)
        self.raist.setText("")
        self.raist.setAlignment(QtCore.Qt.AlignCenter)
        self.raist.setObjectName("raist")
        self.gridLayout_2.addWidget(self.raist, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(alerm)
        QtCore.QMetaObject.connectSlotsByName(alerm)

    def retranslateUi(self, alerm):
        alerm.setWindowTitle(QtGui.QApplication.translate("alerm", "تنبيه للدفع", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("alerm", "الاسم", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("alerm", "الهاتف", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("alerm", "المجموعه", None, QtGui.QApplication.UnicodeUTF8))
        self.ok_bun.setText(QtGui.QApplication.translate("alerm", "مسموح ", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("alerm", "غير مسموح ", None, QtGui.QApplication.UnicodeUTF8))
        self.gp_lbl.setText(QtGui.QApplication.translate("alerm", "لم يتم دفع ", None, QtGui.QApplication.UnicodeUTF8))
        self.tottal_lbl.setText(QtGui.QApplication.translate("alerm", "مسموح او غير مسموح بالحضور", None, QtGui.QApplication.UnicodeUTF8))

import source_rc
