# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/course_info.ui'
#
# Created: Tue Jul 31 20:24:16 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(760, 579)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setStyleSheet("QPushButton\n"
"{\n"
"background-color: #05B963;\n"
"color:#07020D;\n"
"padding:8px;\n"
"border:0px;\n"
"}\n"
"\n"
"\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mony_btn = QtGui.QPushButton(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mony_btn.sizePolicy().hasHeightForWidth())
        self.mony_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Alarabiya Font")
        font.setPointSize(18)
        self.mony_btn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/n/img/Money-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mony_btn.setIcon(icon)
        self.mony_btn.setIconSize(QtCore.QSize(30, 30))
        self.mony_btn.setObjectName("mony_btn")
        self.horizontalLayout_2.addWidget(self.mony_btn)
        self.attend_btn = QtGui.QPushButton(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attend_btn.sizePolicy().hasHeightForWidth())
        self.attend_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Alarabiya Font")
        font.setPointSize(18)
        self.attend_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/n/img/Event Accepted Tentatively Filled-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.attend_btn.setIcon(icon1)
        self.attend_btn.setIconSize(QtCore.QSize(30, 30))
        self.attend_btn.setObjectName("attend_btn")
        self.horizontalLayout_2.addWidget(self.attend_btn)
        self.st_attend_btn = QtGui.QPushButton(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.st_attend_btn.sizePolicy().hasHeightForWidth())
        self.st_attend_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Alarabiya Font")
        font.setPointSize(18)
        self.st_attend_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/n/img/Future-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.st_attend_btn.setIcon(icon2)
        self.st_attend_btn.setIconSize(QtCore.QSize(30, 30))
        self.st_attend_btn.setObjectName("st_attend_btn")
        self.horizontalLayout_2.addWidget(self.st_attend_btn)
        self.students_btn = QtGui.QPushButton(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.students_btn.sizePolicy().hasHeightForWidth())
        self.students_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Alarabiya Font")
        font.setPointSize(18)
        self.students_btn.setFont(font)
        self.students_btn.setStyleSheet("background:#A8B1B2;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/n/img/users-group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.students_btn.setIcon(icon3)
        self.students_btn.setIconSize(QtCore.QSize(30, 30))
        self.students_btn.setCheckable(True)
        self.students_btn.setChecked(True)
        self.students_btn.setObjectName("students_btn")
        self.horizontalLayout_2.addWidget(self.students_btn)
        self.verticalLayout.addWidget(self.widget_4)
        self.stackedWidget = QtGui.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.attend = QtGui.QWidget()
        self.attend.setObjectName("attend")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.attend)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_6 = QtGui.QWidget(self.attend)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.course_time_finish_btn = QtGui.QPushButton(self.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_time_finish_btn.sizePolicy().hasHeightForWidth())
        self.course_time_finish_btn.setSizePolicy(sizePolicy)
        self.course_time_finish_btn.setStyleSheet("border:0px;background:#09C18D;color:#fff;")
        self.course_time_finish_btn.setCheckable(True)
        self.course_time_finish_btn.setObjectName("course_time_finish_btn")
        self.horizontalLayout.addWidget(self.course_time_finish_btn)
        self.course_time_btn = QtGui.QPushButton(self.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_time_btn.sizePolicy().hasHeightForWidth())
        self.course_time_btn.setSizePolicy(sizePolicy)
        self.course_time_btn.setStyleSheet("border:0px;background:#35485F;color:#fff;")
        self.course_time_btn.setCheckable(False)
        self.course_time_btn.setChecked(False)
        self.course_time_btn.setObjectName("course_time_btn")
        self.horizontalLayout.addWidget(self.course_time_btn)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.widget_7 = QtGui.QWidget(self.attend)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.start_dt = QtGui.QDateEdit(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_dt.sizePolicy().hasHeightForWidth())
        self.start_dt.setSizePolicy(sizePolicy)
        self.start_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.start_dt.setCalendarPopup(True)
        self.start_dt.setObjectName("start_dt")
        self.horizontalLayout_4.addWidget(self.start_dt)
        self.label_25 = QtGui.QLabel(self.widget_7)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.widget_7)
        self.stackedWidget_2 = QtGui.QStackedWidget(self.attend)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.stackedWidget_2.sizePolicy().hasHeightForWidth())
        self.stackedWidget_2.setSizePolicy(sizePolicy)
        self.stackedWidget_2.setStyleSheet("")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtGui.QWidget()
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.add_btn_dates = QtGui.QPushButton(self.page)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/n/img/Plus-500.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn_dates.setIcon(icon4)
        self.add_btn_dates.setIconSize(QtCore.QSize(30, 30))
        self.add_btn_dates.setFlat(True)
        self.add_btn_dates.setObjectName("add_btn_dates")
        self.verticalLayout_6.addWidget(self.add_btn_dates)
        self.table_dates = QtGui.QTableWidget(self.page)
        self.table_dates.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.table_dates.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_dates.setObjectName("table_dates")
        self.table_dates.setColumnCount(6)
        self.table_dates.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_dates.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_dates.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_dates.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_dates.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_dates.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_dates.setHorizontalHeaderItem(5, item)
        self.verticalLayout_6.addWidget(self.table_dates)
        self.stackedWidget_2.addWidget(self.page)
        self.page_3 = QtGui.QWidget()
        self.page_3.setStyleSheet("")
        self.page_3.setObjectName("page_3")
        self.gridLayout = QtGui.QGridLayout(self.page_3)
        self.gridLayout.setObjectName("gridLayout")
        self.add_btn_days = QtGui.QPushButton(self.page_3)
        self.add_btn_days.setIcon(icon4)
        self.add_btn_days.setIconSize(QtCore.QSize(30, 30))
        self.add_btn_days.setFlat(True)
        self.add_btn_days.setObjectName("add_btn_days")
        self.gridLayout.addWidget(self.add_btn_days, 0, 1, 1, 1)
        self.finish_days = QtGui.QPushButton(self.page_3)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/n/img/Checkmark-512 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.finish_days.setIcon(icon5)
        self.finish_days.setIconSize(QtCore.QSize(30, 30))
        self.finish_days.setFlat(True)
        self.finish_days.setObjectName("finish_days")
        self.gridLayout.addWidget(self.finish_days, 0, 0, 1, 1)
        self.table_days = QtGui.QTableWidget(self.page_3)
        self.table_days.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.table_days.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_days.setObjectName("table_days")
        self.table_days.setColumnCount(4)
        self.table_days.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_days.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_days.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_days.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_days.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.table_days, 1, 0, 1, 2)
        self.stackedWidget_2.addWidget(self.page_3)
        self.verticalLayout_4.addWidget(self.stackedWidget_2)
        self.stackedWidget.addWidget(self.attend)
        self.all_st = QtGui.QWidget()
        self.all_st.setObjectName("all_st")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.all_st)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_11 = QtGui.QWidget(self.all_st)
        self.widget_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_11)
        self.horizontalLayout_5.setSpacing(9)
        self.horizontalLayout_5.setContentsMargins(10, 9, 9, 9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_26 = QtGui.QWidget(self.widget_11)
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_5.addWidget(self.widget_26)
        self.widget_28 = QtGui.QWidget(self.widget_11)
        self.widget_28.setObjectName("widget_28")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_28)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_student_btn = QtGui.QPushButton(self.widget_28)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_student_btn.sizePolicy().hasHeightForWidth())
        self.add_student_btn.setSizePolicy(sizePolicy)
        self.add_student_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_student_btn.setIcon(icon4)
        self.add_student_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_student_btn.setObjectName("add_student_btn")
        self.gridLayout_2.addWidget(self.add_student_btn, 1, 1, 1, 1)
        self.print_btn = QtGui.QPushButton(self.widget_28)
        self.print_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/n/img/Printer Door Open Filled-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.print_btn.setIcon(icon6)
        self.print_btn.setIconSize(QtCore.QSize(30, 30))
        self.print_btn.setObjectName("print_btn")
        self.gridLayout_2.addWidget(self.print_btn, 1, 4, 1, 1)
        self.st_edt_2 = QtGui.QLineEdit(self.widget_28)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.st_edt_2.sizePolicy().hasHeightForWidth())
        self.st_edt_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.st_edt_2.setFont(font)
        self.st_edt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.st_edt_2.setObjectName("st_edt_2")
        self.gridLayout_2.addWidget(self.st_edt_2, 0, 1, 1, 4)
        self.sw_btn = QtGui.QPushButton(self.widget_28)
        self.sw_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/n/img/Recycling-104.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sw_btn.setIcon(icon7)
        self.sw_btn.setIconSize(QtCore.QSize(30, 30))
        self.sw_btn.setObjectName("sw_btn")
        self.gridLayout_2.addWidget(self.sw_btn, 1, 2, 1, 1)
        self.print_students = QtGui.QPushButton(self.widget_28)
        self.print_students.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.print_students.setIcon(icon6)
        self.print_students.setIconSize(QtCore.QSize(30, 30))
        self.print_students.setObjectName("print_students")
        self.gridLayout_2.addWidget(self.print_students, 1, 3, 1, 1)
        self.horizontalLayout_5.addWidget(self.widget_28)
        self.widget_27 = QtGui.QWidget(self.widget_11)
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_5.addWidget(self.widget_27)
        self.verticalLayout_7.addWidget(self.widget_11)
        self.st_cs_table = QtGui.QTableWidget(self.all_st)
        self.st_cs_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.st_cs_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.st_cs_table.setObjectName("st_cs_table")
        self.st_cs_table.setColumnCount(7)
        self.st_cs_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.st_cs_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.st_cs_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.st_cs_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.st_cs_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.st_cs_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.st_cs_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.st_cs_table.setHorizontalHeaderItem(6, item)
        self.verticalLayout_7.addWidget(self.st_cs_table)
        self.stackedWidget.addWidget(self.all_st)
        self.attend_page = QtGui.QWidget()
        self.attend_page.setObjectName("attend_page")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.attend_page)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_12 = QtGui.QWidget(self.attend_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_12)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_14 = QtGui.QWidget(self.widget_12)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_6.addWidget(self.widget_14)
        self.widget_16 = QtGui.QWidget(self.widget_12)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_16)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_23 = QtGui.QWidget(self.widget_16)
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_23)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.st_attend_print_btn = QtGui.QPushButton(self.widget_23)
        self.st_attend_print_btn.setIcon(icon6)
        self.st_attend_print_btn.setIconSize(QtCore.QSize(30, 30))
        self.st_attend_print_btn.setFlat(True)
        self.st_attend_print_btn.setObjectName("st_attend_print_btn")
        self.horizontalLayout_8.addWidget(self.st_attend_print_btn)
        self.abs_btn = QtGui.QPushButton(self.widget_23)
        self.abs_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/n/img/Cancel-500.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abs_btn.setIcon(icon8)
        self.abs_btn.setIconSize(QtCore.QSize(30, 30))
        self.abs_btn.setFlat(True)
        self.abs_btn.setObjectName("abs_btn")
        self.horizontalLayout_8.addWidget(self.abs_btn)
        self.att_btn = QtGui.QPushButton(self.widget_23)
        self.att_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.att_btn.setIcon(icon5)
        self.att_btn.setIconSize(QtCore.QSize(30, 30))
        self.att_btn.setFlat(True)
        self.att_btn.setObjectName("att_btn")
        self.horizontalLayout_8.addWidget(self.att_btn)
        self.st_attend_search_btn = QtGui.QPushButton(self.widget_23)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/n/img/Search-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.st_attend_search_btn.setIcon(icon9)
        self.st_attend_search_btn.setIconSize(QtCore.QSize(30, 30))
        self.st_attend_search_btn.setFlat(True)
        self.st_attend_search_btn.setObjectName("st_attend_search_btn")
        self.horizontalLayout_8.addWidget(self.st_attend_search_btn)
        self.gridLayout_4.addWidget(self.widget_23, 3, 0, 1, 2)
        self.widget = QtGui.QWidget(self.widget_16)
        self.widget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.all_rd = QtGui.QRadioButton(self.widget)
        self.all_rd.setChecked(True)
        self.all_rd.setObjectName("all_rd")
        self.horizontalLayout_3.addWidget(self.all_rd)
        self.attend_rd = QtGui.QRadioButton(self.widget)
        self.attend_rd.setObjectName("attend_rd")
        self.horizontalLayout_3.addWidget(self.attend_rd)
        self.absent_rd = QtGui.QRadioButton(self.widget)
        self.absent_rd.setObjectName("absent_rd")
        self.horizontalLayout_3.addWidget(self.absent_rd)
        self.gridLayout_4.addWidget(self.widget, 1, 0, 1, 2)
        self.attend_day = QtGui.QComboBox(self.widget_16)
        self.attend_day.setObjectName("attend_day")
        self.gridLayout_4.addWidget(self.attend_day, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 1, 1, 1)
        self.line = QtGui.QFrame(self.widget_16)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 2, 0, 1, 2)
        self.horizontalLayout_6.addWidget(self.widget_16)
        self.widget_15 = QtGui.QWidget(self.widget_12)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_6.addWidget(self.widget_15)
        self.verticalLayout_8.addWidget(self.widget_12)
        self.widget_13 = QtGui.QWidget(self.attend_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget_13)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.st_attend_table = QtGui.QTableWidget(self.widget_13)
        self.st_attend_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.st_attend_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.st_attend_table.setObjectName("st_attend_table")
        self.st_attend_table.setColumnCount(4)
        self.st_attend_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.st_attend_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.st_attend_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.st_attend_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.st_attend_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_9.addWidget(self.st_attend_table)
        self.verticalLayout_8.addWidget(self.widget_13)
        self.stackedWidget.addWidget(self.attend_page)
        self.mony_page = QtGui.QWidget()
        self.mony_page.setObjectName("mony_page")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.mony_page)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_18 = QtGui.QWidget(self.mony_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_18)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_19 = QtGui.QWidget(self.widget_18)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_7.addWidget(self.widget_19)
        self.widget_20 = QtGui.QWidget(self.widget_18)
        self.widget_20.setObjectName("widget_20")
        self.gridLayout_5 = QtGui.QGridLayout(self.widget_20)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtGui.QLabel(self.widget_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 1, 1, 1)
        self.bill_day = QtGui.QComboBox(self.widget_20)
        self.bill_day.setObjectName("bill_day")
        self.gridLayout_5.addWidget(self.bill_day, 0, 0, 1, 1)
        self.widget_24 = QtGui.QWidget(self.widget_20)
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_24)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.bill_print_btn = QtGui.QPushButton(self.widget_24)
        self.bill_print_btn.setIcon(icon6)
        self.bill_print_btn.setIconSize(QtCore.QSize(30, 30))
        self.bill_print_btn.setFlat(True)
        self.bill_print_btn.setObjectName("bill_print_btn")
        self.horizontalLayout_9.addWidget(self.bill_print_btn)
        self.bill_search_btn = QtGui.QPushButton(self.widget_24)
        self.bill_search_btn.setIcon(icon9)
        self.bill_search_btn.setIconSize(QtCore.QSize(30, 30))
        self.bill_search_btn.setFlat(True)
        self.bill_search_btn.setObjectName("bill_search_btn")
        self.horizontalLayout_9.addWidget(self.bill_search_btn)
        self.gridLayout_5.addWidget(self.widget_24, 1, 0, 1, 2)
        self.horizontalLayout_7.addWidget(self.widget_20)
        self.widget_21 = QtGui.QWidget(self.widget_18)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_7.addWidget(self.widget_21)
        self.verticalLayout_11.addWidget(self.widget_18)
        self.widget_17 = QtGui.QWidget(self.mony_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.widget_17.sizePolicy().hasHeightForWidth())
        self.widget_17.setSizePolicy(sizePolicy)
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widget_17)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.bill_table = QtGui.QTableWidget(self.widget_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.bill_table.sizePolicy().hasHeightForWidth())
        self.bill_table.setSizePolicy(sizePolicy)
        self.bill_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bill_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.bill_table.setObjectName("bill_table")
        self.bill_table.setColumnCount(7)
        self.bill_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.bill_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.bill_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.bill_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.bill_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.bill_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.bill_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.bill_table.setHorizontalHeaderItem(6, item)
        self.verticalLayout_10.addWidget(self.bill_table)
        self.widget_22 = QtGui.QWidget(self.widget_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_22.sizePolicy().hasHeightForWidth())
        self.widget_22.setSizePolicy(sizePolicy)
        self.widget_22.setStyleSheet(".QLabel\n"
"{\n"
"background:#000;\n"
"color:#fff;\n"
"}\n"
"")
        self.widget_22.setObjectName("widget_22")
        self.gridLayout_6 = QtGui.QGridLayout(self.widget_22)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(2)
        self.gridLayout_6.setVerticalSpacing(1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_14 = QtGui.QLabel(self.widget_22)
        self.label_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 1, 1, 1, 1)
        self.tottal = QtGui.QLabel(self.widget_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tottal.sizePolicy().hasHeightForWidth())
        self.tottal.setSizePolicy(sizePolicy)
        self.tottal.setAlignment(QtCore.Qt.AlignCenter)
        self.tottal.setObjectName("tottal")
        self.gridLayout_6.addWidget(self.tottal, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget_22)
        self.label_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 2, 1, 1, 1)
        self.baid = QtGui.QLabel(self.widget_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baid.sizePolicy().hasHeightForWidth())
        self.baid.setSizePolicy(sizePolicy)
        self.baid.setAlignment(QtCore.Qt.AlignCenter)
        self.baid.setObjectName("baid")
        self.gridLayout_6.addWidget(self.baid, 1, 0, 1, 1)
        self.rest = QtGui.QLabel(self.widget_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rest.sizePolicy().hasHeightForWidth())
        self.rest.setSizePolicy(sizePolicy)
        self.rest.setAlignment(QtCore.Qt.AlignCenter)
        self.rest.setObjectName("rest")
        self.gridLayout_6.addWidget(self.rest, 2, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.widget_22)
        self.verticalLayout_11.addWidget(self.widget_17)
        self.stackedWidget.addWidget(self.mony_page)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.mony_btn.setText(QtGui.QApplication.translate("Form", "المعاملات المالية", None, QtGui.QApplication.UnicodeUTF8))
        self.attend_btn.setText(QtGui.QApplication.translate("Form", "المواعيد", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_btn.setText(QtGui.QApplication.translate("Form", "حضور و غياب", None, QtGui.QApplication.UnicodeUTF8))
        self.students_btn.setText(QtGui.QApplication.translate("Form", "الطلاب", None, QtGui.QApplication.UnicodeUTF8))
        self.course_time_finish_btn.setText(QtGui.QApplication.translate("Form", "انهاء المواعيد", None, QtGui.QApplication.UnicodeUTF8))
        self.course_time_btn.setText(QtGui.QApplication.translate("Form", "اختيار المواعيد", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Form", "بداية الدورة", None, QtGui.QApplication.UnicodeUTF8))
        self.add_btn_dates.setText(QtGui.QApplication.translate("Form", "اضافة", None, QtGui.QApplication.UnicodeUTF8))
        self.table_dates.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "التاريخ", None, QtGui.QApplication.UnicodeUTF8))
        self.table_dates.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "اليوم", None, QtGui.QApplication.UnicodeUTF8))
        self.table_dates.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "من", None, QtGui.QApplication.UnicodeUTF8))
        self.table_dates.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "الى", None, QtGui.QApplication.UnicodeUTF8))
        self.table_dates.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "حذف", None, QtGui.QApplication.UnicodeUTF8))
        self.table_dates.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "تعديل", None, QtGui.QApplication.UnicodeUTF8))
        self.add_btn_days.setText(QtGui.QApplication.translate("Form", "اضافة", None, QtGui.QApplication.UnicodeUTF8))
        self.finish_days.setText(QtGui.QApplication.translate("Form", "انهاء", None, QtGui.QApplication.UnicodeUTF8))
        self.table_days.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "اليوم", None, QtGui.QApplication.UnicodeUTF8))
        self.table_days.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "من", None, QtGui.QApplication.UnicodeUTF8))
        self.table_days.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "الى", None, QtGui.QApplication.UnicodeUTF8))
        self.table_days.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "حذف", None, QtGui.QApplication.UnicodeUTF8))
        self.add_student_btn.setText(QtGui.QApplication.translate("Form", "اضافة طالب", None, QtGui.QApplication.UnicodeUTF8))
        self.print_btn.setText(QtGui.QApplication.translate("Form", "طباعة الباركود", None, QtGui.QApplication.UnicodeUTF8))
        self.st_edt_2.setPlaceholderText(QtGui.QApplication.translate("Form", "الاسم - الهاتف - الباركود", None, QtGui.QApplication.UnicodeUTF8))
        self.sw_btn.setText(QtGui.QApplication.translate("Form", "نقل كل الطلاب", None, QtGui.QApplication.UnicodeUTF8))
        self.print_students.setText(QtGui.QApplication.translate("Form", "طباعة الطلاب", None, QtGui.QApplication.UnicodeUTF8))
        self.st_cs_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "الاسم", None, QtGui.QApplication.UnicodeUTF8))
        self.st_cs_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "الهاتف", None, QtGui.QApplication.UnicodeUTF8))
        self.st_cs_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "الباركود", None, QtGui.QApplication.UnicodeUTF8))
        self.st_cs_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "المقرر دفعه", None, QtGui.QApplication.UnicodeUTF8))
        self.st_cs_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "حذف", None, QtGui.QApplication.UnicodeUTF8))
        self.st_cs_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "طباعة", None, QtGui.QApplication.UnicodeUTF8))
        self.st_cs_table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "نقل الطالب", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_print_btn.setText(QtGui.QApplication.translate("Form", "طباعة", None, QtGui.QApplication.UnicodeUTF8))
        self.abs_btn.setText(QtGui.QApplication.translate("Form", "غياب الكل", None, QtGui.QApplication.UnicodeUTF8))
        self.att_btn.setText(QtGui.QApplication.translate("Form", "تحضير الكل", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_search_btn.setText(QtGui.QApplication.translate("Form", "بحث", None, QtGui.QApplication.UnicodeUTF8))
        self.all_rd.setText(QtGui.QApplication.translate("Form", "الكل", None, QtGui.QApplication.UnicodeUTF8))
        self.attend_rd.setText(QtGui.QApplication.translate("Form", "حضور", None, QtGui.QApplication.UnicodeUTF8))
        self.absent_rd.setText(QtGui.QApplication.translate("Form", "غياب", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "اختر الحصة", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "الاسم", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "الهاتف", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "الباركود", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "الحالة", None, QtGui.QApplication.UnicodeUTF8))
        self.bill_print_btn.setText(QtGui.QApplication.translate("Form", "طباعة", None, QtGui.QApplication.UnicodeUTF8))
        self.bill_search_btn.setText(QtGui.QApplication.translate("Form", "بحث", None, QtGui.QApplication.UnicodeUTF8))
        self.bill_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "الاسم", None, QtGui.QApplication.UnicodeUTF8))
        self.bill_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "الهاتف", None, QtGui.QApplication.UnicodeUTF8))
        self.bill_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "الباركود", None, QtGui.QApplication.UnicodeUTF8))
        self.bill_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "المقرر دفعة", None, QtGui.QApplication.UnicodeUTF8))
        self.bill_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "المدفوع", None, QtGui.QApplication.UnicodeUTF8))
        self.bill_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "الباقى", None, QtGui.QApplication.UnicodeUTF8))
        self.bill_table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "دفع", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "المدفوع", None, QtGui.QApplication.UnicodeUTF8))
        self.tottal.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "المقرر دفعه", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "الباقى", None, QtGui.QApplication.UnicodeUTF8))
        self.baid.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.rest.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))

import source_rc
