# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/exam_info.ui'
#
# Created: Mon Jun 25 19:48:02 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(760, 579)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setStyleSheet("QPushButton\n"
"{\n"
"background-color: #05B963;\n"
"color:#07020D;\n"
"padding:8px;\n"
"border:0px;\n"
"}\n"
"QPushButton::activated\n"
"{\n"
"background-color: #000;\n"
"color:#07020D;\n"
"padding:8px;\n"
"border:0px;\n"
"}\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.attend_btn = QtGui.QPushButton(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attend_btn.sizePolicy().hasHeightForWidth())
        self.attend_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Alarabiya Font")
        font.setPointSize(18)
        self.attend_btn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/n/img/Event Accepted Tentatively Filled-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.attend_btn.setIcon(icon)
        self.attend_btn.setIconSize(QtCore.QSize(30, 30))
        self.attend_btn.setObjectName("attend_btn")
        self.horizontalLayout_2.addWidget(self.attend_btn)
        self.st_attend_btn = QtGui.QPushButton(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.st_attend_btn.sizePolicy().hasHeightForWidth())
        self.st_attend_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Alarabiya Font")
        font.setPointSize(18)
        self.st_attend_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/n/img/Future-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.st_attend_btn.setIcon(icon1)
        self.st_attend_btn.setIconSize(QtCore.QSize(30, 30))
        self.st_attend_btn.setObjectName("st_attend_btn")
        self.horizontalLayout_2.addWidget(self.st_attend_btn)
        self.gps_btn = QtGui.QPushButton(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gps_btn.sizePolicy().hasHeightForWidth())
        self.gps_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Alarabiya Font")
        font.setPointSize(18)
        self.gps_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/n/img/users-group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gps_btn.setIcon(icon2)
        self.gps_btn.setIconSize(QtCore.QSize(30, 30))
        self.gps_btn.setObjectName("gps_btn")
        self.horizontalLayout_2.addWidget(self.gps_btn)
        self.verticalLayout.addWidget(self.widget_4)
        self.stackedWidget = QtGui.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.attend = QtGui.QWidget()
        self.attend.setObjectName("attend")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.attend)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_6 = QtGui.QWidget(self.attend)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.course_time_finish_btn = QtGui.QPushButton(self.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_time_finish_btn.sizePolicy().hasHeightForWidth())
        self.course_time_finish_btn.setSizePolicy(sizePolicy)
        self.course_time_finish_btn.setStyleSheet("border:0px;background:#09C18D;color:#fff;")
        self.course_time_finish_btn.setCheckable(True)
        self.course_time_finish_btn.setObjectName("course_time_finish_btn")
        self.horizontalLayout.addWidget(self.course_time_finish_btn)
        self.course_time_btn = QtGui.QPushButton(self.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_time_btn.sizePolicy().hasHeightForWidth())
        self.course_time_btn.setSizePolicy(sizePolicy)
        self.course_time_btn.setStyleSheet("border:0px;background:#35485F;color:#fff;")
        self.course_time_btn.setCheckable(False)
        self.course_time_btn.setChecked(False)
        self.course_time_btn.setObjectName("course_time_btn")
        self.horizontalLayout.addWidget(self.course_time_btn)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.widget_7 = QtGui.QWidget(self.attend)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.start_dt = QtGui.QDateEdit(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_dt.sizePolicy().hasHeightForWidth())
        self.start_dt.setSizePolicy(sizePolicy)
        self.start_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.start_dt.setCalendarPopup(True)
        self.start_dt.setObjectName("start_dt")
        self.horizontalLayout_4.addWidget(self.start_dt)
        self.label_25 = QtGui.QLabel(self.widget_7)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.widget_7)
        self.stackedWidget_2 = QtGui.QStackedWidget(self.attend)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.stackedWidget_2.sizePolicy().hasHeightForWidth())
        self.stackedWidget_2.setSizePolicy(sizePolicy)
        self.stackedWidget_2.setStyleSheet("")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtGui.QWidget()
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.add_btn_dates = QtGui.QPushButton(self.page)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/n/img/Plus-500.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn_dates.setIcon(icon3)
        self.add_btn_dates.setIconSize(QtCore.QSize(30, 30))
        self.add_btn_dates.setFlat(True)
        self.add_btn_dates.setObjectName("add_btn_dates")
        self.verticalLayout_6.addWidget(self.add_btn_dates)
        self.table_dates = QtGui.QTableWidget(self.page)
        self.table_dates.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.table_dates.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_dates.setObjectName("table_dates")
        self.table_dates.setColumnCount(6)
        self.table_dates.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_dates.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_dates.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_dates.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_dates.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_dates.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_dates.setHorizontalHeaderItem(5, item)
        self.verticalLayout_6.addWidget(self.table_dates)
        self.finish_dates = QtGui.QPushButton(self.page)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/n/img/Save-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.finish_dates.setIcon(icon4)
        self.finish_dates.setIconSize(QtCore.QSize(30, 30))
        self.finish_dates.setFlat(True)
        self.finish_dates.setObjectName("finish_dates")
        self.verticalLayout_6.addWidget(self.finish_dates)
        self.stackedWidget_2.addWidget(self.page)
        self.page_3 = QtGui.QWidget()
        self.page_3.setStyleSheet("")
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.add_btn_days = QtGui.QPushButton(self.page_3)
        self.add_btn_days.setIcon(icon3)
        self.add_btn_days.setIconSize(QtCore.QSize(30, 30))
        self.add_btn_days.setFlat(True)
        self.add_btn_days.setObjectName("add_btn_days")
        self.verticalLayout_5.addWidget(self.add_btn_days)
        self.table_days = QtGui.QTableWidget(self.page_3)
        self.table_days.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.table_days.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_days.setObjectName("table_days")
        self.table_days.setColumnCount(4)
        self.table_days.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_days.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_days.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_days.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_days.setHorizontalHeaderItem(3, item)
        self.verticalLayout_5.addWidget(self.table_days)
        self.finish_days = QtGui.QPushButton(self.page_3)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/n/img/Checkmark-512 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.finish_days.setIcon(icon5)
        self.finish_days.setIconSize(QtCore.QSize(30, 30))
        self.finish_days.setFlat(True)
        self.finish_days.setObjectName("finish_days")
        self.verticalLayout_5.addWidget(self.finish_days)
        self.stackedWidget_2.addWidget(self.page_3)
        self.verticalLayout_4.addWidget(self.stackedWidget_2)
        self.back_btn = QtGui.QPushButton(self.attend)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/n/img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon6)
        self.back_btn.setIconSize(QtCore.QSize(30, 30))
        self.back_btn.setFlat(True)
        self.back_btn.setObjectName("back_btn")
        self.verticalLayout_4.addWidget(self.back_btn)
        self.stackedWidget.addWidget(self.attend)
        self.all_st = QtGui.QWidget()
        self.all_st.setObjectName("all_st")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.all_st)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_11 = QtGui.QWidget(self.all_st)
        self.widget_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_11)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_26 = QtGui.QWidget(self.widget_11)
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_5.addWidget(self.widget_26)
        self.widget_25 = QtGui.QWidget(self.widget_11)
        self.widget_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_25.setStyleSheet("")
        self.widget_25.setObjectName("widget_25")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_25)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.st_edt_2 = QtGui.QLineEdit(self.widget_25)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.st_edt_2.sizePolicy().hasHeightForWidth())
        self.st_edt_2.setSizePolicy(sizePolicy)
        self.st_edt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.st_edt_2.setObjectName("st_edt_2")
        self.horizontalLayout_10.addWidget(self.st_edt_2)
        self.horizontalLayout_5.addWidget(self.widget_25)
        self.widget_27 = QtGui.QWidget(self.widget_11)
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_5.addWidget(self.widget_27)
        self.verticalLayout_7.addWidget(self.widget_11)
        self.st_cs_table = QtGui.QTableWidget(self.all_st)
        self.st_cs_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.st_cs_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.st_cs_table.setObjectName("st_cs_table")
        self.st_cs_table.setColumnCount(2)
        self.st_cs_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.st_cs_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.st_cs_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_7.addWidget(self.st_cs_table)
        self.stackedWidget.addWidget(self.all_st)
        self.attend_page = QtGui.QWidget()
        self.attend_page.setObjectName("attend_page")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.attend_page)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_12 = QtGui.QWidget(self.attend_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_12)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_14 = QtGui.QWidget(self.widget_12)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_6.addWidget(self.widget_14)
        self.widget_16 = QtGui.QWidget(self.widget_12)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_16)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gp_name = QtGui.QComboBox(self.widget_16)
        self.gp_name.setObjectName("gp_name")
        self.gridLayout_4.addWidget(self.gp_name, 0, 0, 1, 1)
        self.widget_23 = QtGui.QWidget(self.widget_16)
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_23)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.st_attend_print_btn = QtGui.QPushButton(self.widget_23)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/n/img/Printer Door Open Filled-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.st_attend_print_btn.setIcon(icon7)
        self.st_attend_print_btn.setIconSize(QtCore.QSize(30, 30))
        self.st_attend_print_btn.setFlat(True)
        self.st_attend_print_btn.setObjectName("st_attend_print_btn")
        self.horizontalLayout_8.addWidget(self.st_attend_print_btn)
        self.st_attend_search_btn = QtGui.QPushButton(self.widget_23)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/n/img/Search-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.st_attend_search_btn.setIcon(icon8)
        self.st_attend_search_btn.setIconSize(QtCore.QSize(30, 30))
        self.st_attend_search_btn.setFlat(True)
        self.st_attend_search_btn.setObjectName("st_attend_search_btn")
        self.horizontalLayout_8.addWidget(self.st_attend_search_btn)
        self.gridLayout_4.addWidget(self.widget_23, 2, 0, 1, 2)
        self.label_8 = QtGui.QLabel(self.widget_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget_16)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 1, 1, 1)
        self.exam_day = QtGui.QComboBox(self.widget_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exam_day.sizePolicy().hasHeightForWidth())
        self.exam_day.setSizePolicy(sizePolicy)
        self.exam_day.setObjectName("exam_day")
        self.gridLayout_4.addWidget(self.exam_day, 1, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.widget_16)
        self.widget_15 = QtGui.QWidget(self.widget_12)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_6.addWidget(self.widget_15)
        self.verticalLayout_8.addWidget(self.widget_12)
        self.widget_13 = QtGui.QWidget(self.attend_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget_13)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.st_attend_table = QtGui.QTableWidget(self.widget_13)
        self.st_attend_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.st_attend_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.st_attend_table.setObjectName("st_attend_table")
        self.st_attend_table.setColumnCount(7)
        self.st_attend_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.st_attend_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.st_attend_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.st_attend_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.st_attend_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.st_attend_table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.st_attend_table.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.st_attend_table.setHorizontalHeaderItem(6, item)
        self.verticalLayout_9.addWidget(self.st_attend_table)
        self.verticalLayout_8.addWidget(self.widget_13)
        self.stackedWidget.addWidget(self.attend_page)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.attend_btn.setText(QtGui.QApplication.translate("Form", "المواعيد", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_btn.setText(QtGui.QApplication.translate("Form", "حضور و درجات", None, QtGui.QApplication.UnicodeUTF8))
        self.gps_btn.setText(QtGui.QApplication.translate("Form", "المجموعات", None, QtGui.QApplication.UnicodeUTF8))
        self.course_time_finish_btn.setText(QtGui.QApplication.translate("Form", "انهاء المواعيد", None, QtGui.QApplication.UnicodeUTF8))
        self.course_time_btn.setText(QtGui.QApplication.translate("Form", "اختيار المواعيد", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Form", "بداية الاختبار", None, QtGui.QApplication.UnicodeUTF8))
        self.add_btn_dates.setText(QtGui.QApplication.translate("Form", "اضافة", None, QtGui.QApplication.UnicodeUTF8))
        self.table_dates.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "التاريخ", None, QtGui.QApplication.UnicodeUTF8))
        self.table_dates.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "اليوم", None, QtGui.QApplication.UnicodeUTF8))
        self.table_dates.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "من", None, QtGui.QApplication.UnicodeUTF8))
        self.table_dates.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "الى", None, QtGui.QApplication.UnicodeUTF8))
        self.table_dates.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "حذف", None, QtGui.QApplication.UnicodeUTF8))
        self.table_dates.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "تعديل", None, QtGui.QApplication.UnicodeUTF8))
        self.finish_dates.setText(QtGui.QApplication.translate("Form", "حفظ", None, QtGui.QApplication.UnicodeUTF8))
        self.add_btn_days.setText(QtGui.QApplication.translate("Form", "اضافة", None, QtGui.QApplication.UnicodeUTF8))
        self.table_days.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "اليوم", None, QtGui.QApplication.UnicodeUTF8))
        self.table_days.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "من", None, QtGui.QApplication.UnicodeUTF8))
        self.table_days.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "الى", None, QtGui.QApplication.UnicodeUTF8))
        self.table_days.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "حذف", None, QtGui.QApplication.UnicodeUTF8))
        self.finish_days.setText(QtGui.QApplication.translate("Form", "انهاء", None, QtGui.QApplication.UnicodeUTF8))
        self.back_btn.setText(QtGui.QApplication.translate("Form", "رجوع", None, QtGui.QApplication.UnicodeUTF8))
        self.st_edt_2.setPlaceholderText(QtGui.QApplication.translate("Form", "الاسم", None, QtGui.QApplication.UnicodeUTF8))
        self.st_cs_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "المجموعة", None, QtGui.QApplication.UnicodeUTF8))
        self.st_cs_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "حذف", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_print_btn.setText(QtGui.QApplication.translate("Form", "طباعة", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_search_btn.setText(QtGui.QApplication.translate("Form", "بحث", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "اختر المجموعة", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "اختر الحصة", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "الاسم", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "الهاتف", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "الباركود", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "الحالة", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "الدرجة العظمى", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_table.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "درجة الطالب", None, QtGui.QApplication.UnicodeUTF8))
        self.st_attend_table.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "تغيير الدرجة", None, QtGui.QApplication.UnicodeUTF8))

import source_rc
