# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/gp_report.ui'
#
# Created: Wed Feb 07 21:36:56 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(907, 575)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.baid_lbl = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baid_lbl.sizePolicy().hasHeightForWidth())
        self.baid_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(20)
        self.baid_lbl.setFont(font)
        self.baid_lbl.setText("")
        self.baid_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.baid_lbl.setObjectName("baid_lbl")
        self.gridLayout_2.addWidget(self.baid_lbl, 2, 0, 1, 1)
        self.all_items = QtGui.QTableWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_items.sizePolicy().hasHeightForWidth())
        self.all_items.setSizePolicy(sizePolicy)
        self.all_items.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.all_items.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.all_items.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.all_items.setObjectName("all_items")
        self.all_items.setColumnCount(7)
        self.all_items.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(6, item)
        self.all_items.horizontalHeader().setCascadingSectionResizes(True)
        self.all_items.horizontalHeader().setDefaultSectionSize(150)
        self.all_items.horizontalHeader().setMinimumSectionSize(100)
        self.all_items.verticalHeader().setMinimumSectionSize(23)
        self.all_items.verticalHeader().setSortIndicatorShown(False)
        self.all_items.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.all_items, 1, 0, 1, 2)
        self.widget_51 = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_51.sizePolicy().hasHeightForWidth())
        self.widget_51.setSizePolicy(sizePolicy)
        self.widget_51.setObjectName("widget_51")
        self.gridLayout_23 = QtGui.QGridLayout(self.widget_51)
        self.gridLayout_23.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_92 = QtGui.QLabel(self.widget_51)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_92.sizePolicy().hasHeightForWidth())
        self.label_92.setSizePolicy(sizePolicy)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.gridLayout_23.addWidget(self.label_92, 0, 2, 1, 1)
        self.label_93 = QtGui.QLabel(self.widget_51)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_93.sizePolicy().hasHeightForWidth())
        self.label_93.setSizePolicy(sizePolicy)
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.gridLayout_23.addWidget(self.label_93, 1, 2, 1, 1)
        self.end_dt = QtGui.QDateEdit(self.widget_51)
        self.end_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.end_dt.setCalendarPopup(True)
        self.end_dt.setObjectName("end_dt")
        self.gridLayout_23.addWidget(self.end_dt, 1, 1, 1, 1)
        self.st_dt = QtGui.QDateEdit(self.widget_51)
        self.st_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.st_dt.setCalendarPopup(True)
        self.st_dt.setObjectName("st_dt")
        self.gridLayout_23.addWidget(self.st_dt, 0, 1, 1, 1)
        self.course_cmb = QtGui.QComboBox(self.widget_51)
        self.course_cmb.setObjectName("course_cmb")
        self.gridLayout_23.addWidget(self.course_cmb, 2, 1, 1, 1)
        self.widget_54 = QtGui.QWidget(self.widget_51)
        self.widget_54.setObjectName("widget_54")
        self.gridLayout_23.addWidget(self.widget_54, 1, 0, 1, 1)
        self.widget_55 = QtGui.QWidget(self.widget_51)
        self.widget_55.setObjectName("widget_55")
        self.gridLayout_23.addWidget(self.widget_55, 1, 4, 1, 1)
        self.search_btn = QtGui.QPushButton(self.widget_51)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/n/img/Search-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon)
        self.search_btn.setIconSize(QtCore.QSize(50, 50))
        self.search_btn.setFlat(True)
        self.search_btn.setObjectName("search_btn")
        self.gridLayout_23.addWidget(self.search_btn, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget_51, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "رقم الطالب", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "اسم الطالب", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "غياب المجموعات", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "غياب الاختبارات", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "درجات الاختبارات", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "المعاملات الماديه", None, QtGui.QApplication.UnicodeUTF8))
        self.label_92.setText(QtGui.QApplication.translate("Form", "من", None, QtGui.QApplication.UnicodeUTF8))
        self.label_93.setText(QtGui.QApplication.translate("Form", "الى", None, QtGui.QApplication.UnicodeUTF8))
        self.search_btn.setText(QtGui.QApplication.translate("Form", "بحث", None, QtGui.QApplication.UnicodeUTF8))

import source_rc
import source_rc
