# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/permissions.ui'
#
# Created: Sun Jul 30 13:37:32 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 436)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtGui.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_11 = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_12 = QtGui.QGridLayout(self.widget_11)
        self.gridLayout_12.setContentsMargins(9, 25, -1, -1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.bottom_scroll = QtGui.QScrollArea(self.widget_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.bottom_scroll.sizePolicy().hasHeightForWidth())
        self.bottom_scroll.setSizePolicy(sizePolicy)
        self.bottom_scroll.setStyleSheet(".QWidget\n"
"{\n"
"background:#E8E8E4;\n"
"}\n"
".QPushButton\n"
"{\n"
"background:#4ECDC4;\n"
"color:#000;\n"
"\n"
"}")
        self.bottom_scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.bottom_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.bottom_scroll.setWidgetResizable(True)
        self.bottom_scroll.setObjectName("bottom_scroll")
        self.bottom_w = QtGui.QWidget()
        self.bottom_w.setGeometry(QtCore.QRect(0, 0, 353, 400))
        self.bottom_w.setObjectName("bottom_w")
        self.gridLayout_9 = QtGui.QGridLayout(self.bottom_w)
        self.gridLayout_9.setSpacing(30)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.bottom_scroll.setWidget(self.bottom_w)
        self.gridLayout_12.addWidget(self.bottom_scroll, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_11, 2, 0, 1, 1)
        self.edt = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.edt.sizePolicy().hasHeightForWidth())
        self.edt.setSizePolicy(sizePolicy)
        self.edt.setObjectName("edt")
        self.gridLayout_33 = QtGui.QGridLayout(self.edt)
        self.gridLayout_33.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_33.setSpacing(0)
        self.gridLayout_33.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.widget_156 = QtGui.QWidget(self.edt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.widget_156.sizePolicy().hasHeightForWidth())
        self.widget_156.setSizePolicy(sizePolicy)
        self.widget_156.setObjectName("widget_156")
        self.gridLayout = QtGui.QGridLayout(self.widget_156)
        self.gridLayout.setContentsMargins(-1, 25, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtGui.QWidget(self.widget_156)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.udelet = QtGui.QPushButton(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.udelet.sizePolicy().hasHeightForWidth())
        self.udelet.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.udelet.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/n/img/Cancel-500.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.udelet.setIcon(icon)
        self.udelet.setIconSize(QtCore.QSize(50, 50))
        self.udelet.setFlat(True)
        self.udelet.setObjectName("udelet")
        self.horizontalLayout_2.addWidget(self.udelet)
        self.uedite = QtGui.QPushButton(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uedite.sizePolicy().hasHeightForWidth())
        self.uedite.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.uedite.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/n/img/Checkmark-512 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uedite.setIcon(icon1)
        self.uedite.setIconSize(QtCore.QSize(50, 50))
        self.uedite.setFlat(True)
        self.uedite.setObjectName("uedite")
        self.horizontalLayout_2.addWidget(self.uedite)
        self.gridLayout.addWidget(self.widget_3, 7, 0, 1, 3)
        self.uname = QtGui.QLineEdit(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uname.sizePolicy().hasHeightForWidth())
        self.uname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.uname.setFont(font)
        self.uname.setAlignment(QtCore.Qt.AlignCenter)
        self.uname.setObjectName("uname")
        self.gridLayout.addWidget(self.uname, 4, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 2, 1, 1)
        self.ufname = QtGui.QLineEdit(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ufname.sizePolicy().hasHeightForWidth())
        self.ufname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.ufname.setFont(font)
        self.ufname.setAlignment(QtCore.Qt.AlignCenter)
        self.ufname.setObjectName("ufname")
        self.gridLayout.addWidget(self.ufname, 3, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 2, 1, 1)
        self.widget_2 = QtGui.QWidget(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.uadminradio = QtGui.QRadioButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.uadminradio.setFont(font)
        self.uadminradio.setMouseTracking(True)
        self.uadminradio.setStyleSheet("")
        self.uadminradio.setChecked(True)
        self.uadminradio.setObjectName("uadminradio")
        self.horizontalLayout_30.addWidget(self.uadminradio)
        self.userradio = QtGui.QRadioButton(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.userradio.setFont(font)
        self.userradio.setChecked(False)
        self.userradio.setObjectName("userradio")
        self.horizontalLayout_30.addWidget(self.userradio)
        self.gridLayout.addWidget(self.widget_2, 6, 0, 1, 3)
        self.uid = QtGui.QLabel(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uid.sizePolicy().hasHeightForWidth())
        self.uid.setSizePolicy(sizePolicy)
        self.uid.setText("")
        self.uid.setObjectName("uid")
        self.gridLayout.addWidget(self.uid, 1, 0, 1, 3)
        self.label = QtGui.QLabel(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 2, 1, 1)
        self.upass = QtGui.QLineEdit(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upass.sizePolicy().hasHeightForWidth())
        self.upass.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.upass.setFont(font)
        self.upass.setAlignment(QtCore.Qt.AlignCenter)
        self.upass.setObjectName("upass")
        self.gridLayout.addWidget(self.upass, 5, 0, 1, 2)
        self.widget_4 = QtGui.QWidget(self.widget_156)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.permissions_btn = QtGui.QPushButton(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.permissions_btn.sizePolicy().hasHeightForWidth())
        self.permissions_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.permissions_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/n/img/Lock-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.permissions_btn.setIcon(icon2)
        self.permissions_btn.setIconSize(QtCore.QSize(50, 50))
        self.permissions_btn.setFlat(True)
        self.permissions_btn.setObjectName("permissions_btn")
        self.verticalLayout_2.addWidget(self.permissions_btn)
        self.gridLayout.addWidget(self.widget_4, 8, 0, 1, 3)
        self.widget_5 = QtGui.QWidget(self.widget_156)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.uadd = QtGui.QPushButton(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uadd.sizePolicy().hasHeightForWidth())
        self.uadd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.uadd.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/n/img/Plus-500.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uadd.setIcon(icon3)
        self.uadd.setIconSize(QtCore.QSize(50, 50))
        self.uadd.setFlat(True)
        self.uadd.setObjectName("uadd")
        self.verticalLayout.addWidget(self.uadd)
        self.gridLayout.addWidget(self.widget_5, 0, 0, 1, 3)
        self.gridLayout_33.addWidget(self.widget_156, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.edt, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.ufname, self.uname)
        Form.setTabOrder(self.uname, self.upass)
        Form.setTabOrder(self.upass, self.uadminradio)
        Form.setTabOrder(self.uadminradio, self.userradio)
        Form.setTabOrder(self.userradio, self.uedite)
        Form.setTabOrder(self.uedite, self.udelet)
        Form.setTabOrder(self.udelet, self.bottom_scroll)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.udelet.setToolTip(QtGui.QApplication.translate("Form", "حذف مستخدم", None, QtGui.QApplication.UnicodeUTF8))
        self.udelet.setText(QtGui.QApplication.translate("Form", "حذف", None, QtGui.QApplication.UnicodeUTF8))
        self.uedite.setToolTip(QtGui.QApplication.translate("Form", "تعديل مستخدم", None, QtGui.QApplication.UnicodeUTF8))
        self.uedite.setText(QtGui.QApplication.translate("Form", "تعديل", None, QtGui.QApplication.UnicodeUTF8))
        self.uname.setPlaceholderText(QtGui.QApplication.translate("Form", "اسم الدخول", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "اسم الدخول", None, QtGui.QApplication.UnicodeUTF8))
        self.ufname.setPlaceholderText(QtGui.QApplication.translate("Form", "الاسم كامل", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "الرقم السرى", None, QtGui.QApplication.UnicodeUTF8))
        self.uadminradio.setText(QtGui.QApplication.translate("Form", "مدير", None, QtGui.QApplication.UnicodeUTF8))
        self.userradio.setText(QtGui.QApplication.translate("Form", "مستخدم", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "الاسم كامل", None, QtGui.QApplication.UnicodeUTF8))
        self.upass.setPlaceholderText(QtGui.QApplication.translate("Form", "الرقم السرى", None, QtGui.QApplication.UnicodeUTF8))
        self.permissions_btn.setText(QtGui.QApplication.translate("Form", "الصلاحيات", None, QtGui.QApplication.UnicodeUTF8))
        self.uadd.setToolTip(QtGui.QApplication.translate("Form", "اضافة مستخدم", None, QtGui.QApplication.UnicodeUTF8))
        self.uadd.setText(QtGui.QApplication.translate("Form", "اضافة", None, QtGui.QApplication.UnicodeUTF8))

import source_rc
