# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/perm_set.ui'
#
# Created: Wed Aug  9 18:17:25 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(245, 644)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/n/img/home.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtGui.QWidget(Form)
        self.widget.setStyleSheet(" .QWidget{\n"
"background: #44D9E6;color: black;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setContentsMargins(0, 3, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtGui.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_full_name = QtGui.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.user_full_name.setFont(font)
        self.user_full_name.setText("")
        self.user_full_name.setAlignment(QtCore.Qt.AlignCenter)
        self.user_full_name.setObjectName("user_full_name")
        self.horizontalLayout.addWidget(self.user_full_name)
        self.user_id = QtGui.QLabel(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_id.sizePolicy().hasHeightForWidth())
        self.user_id.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.user_id.setFont(font)
        self.user_id.setText("")
        self.user_id.setAlignment(QtCore.Qt.AlignCenter)
        self.user_id.setObjectName("user_id")
        self.horizontalLayout.addWidget(self.user_id)
        self.verticalLayout.addWidget(self.widget_4)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.widget_3 = QtGui.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtGui.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.times_ck = QtGui.QCheckBox(self.widget_3)
        self.times_ck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.times_ck.setChecked(True)
        self.times_ck.setObjectName("times_ck")
        self.gridLayout.addWidget(self.times_ck, 2, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.end_dt = QtGui.QTimeEdit(self.widget_3)
        self.end_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.end_dt.setObjectName("end_dt")
        self.gridLayout.addWidget(self.end_dt, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 1)
        self.st_dt = QtGui.QTimeEdit(self.widget_3)
        self.st_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.st_dt.setTime(QtCore.QTime(0, 0, 0))
        self.st_dt.setObjectName("st_dt")
        self.gridLayout.addWidget(self.st_dt, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_4 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.perm_table = QtGui.QTableWidget(self.widget)
        self.perm_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.perm_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.perm_table.setObjectName("perm_table")
        self.perm_table.setColumnCount(2)
        self.perm_table.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.perm_table.setItem(4, 0, item)
        self.verticalLayout.addWidget(self.perm_table)
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.perm_set_btn = QtGui.QPushButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perm_set_btn.sizePolicy().hasHeightForWidth())
        self.perm_set_btn.setSizePolicy(sizePolicy)
        self.perm_set_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/n/img/Checkmark-512 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.perm_set_btn.setIcon(icon1)
        self.perm_set_btn.setIconSize(QtCore.QSize(30, 30))
        self.perm_set_btn.setFlat(True)
        self.perm_set_btn.setObjectName("perm_set_btn")
        self.verticalLayout_3.addWidget(self.perm_set_btn)
        self.verticalLayout.addWidget(self.widget_2)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "اعطاء صلاحيات", None, QtGui.QApplication.UnicodeUTF8))
        self.times_ck.setText(QtGui.QApplication.translate("Form", "تفعيل نظام الوردية", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "الى", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "فترة العمل", None, QtGui.QApplication.UnicodeUTF8))
        self.end_dt.setDisplayFormat(QtGui.QApplication.translate("Form", "hh:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "من", None, QtGui.QApplication.UnicodeUTF8))
        self.st_dt.setDisplayFormat(QtGui.QApplication.translate("Form", "hh:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "اعطاء الصلاحيات", None, QtGui.QApplication.UnicodeUTF8))
        self.perm_table.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.perm_table.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.perm_table.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.perm_table.verticalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.perm_table.verticalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.perm_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "الصفحة", None, QtGui.QApplication.UnicodeUTF8))
        self.perm_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "امكانية الدخول", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.perm_table.isSortingEnabled()
        self.perm_table.setSortingEnabled(False)
        self.perm_table.item(0, 0).setText(QtGui.QApplication.translate("Form", "حضور الطلاب", None, QtGui.QApplication.UnicodeUTF8))
        self.perm_table.item(1, 0).setText(QtGui.QApplication.translate("Form", "المجموعات", None, QtGui.QApplication.UnicodeUTF8))
        self.perm_table.item(2, 0).setText(QtGui.QApplication.translate("Form", "الطالب", None, QtGui.QApplication.UnicodeUTF8))
        self.perm_table.item(3, 0).setText(QtGui.QApplication.translate("Form", "تقرير المالية", None, QtGui.QApplication.UnicodeUTF8))
        self.perm_table.item(4, 0).setText(QtGui.QApplication.translate("Form", "الاختبارات", None, QtGui.QApplication.UnicodeUTF8))
        self.perm_table.setSortingEnabled(__sortingEnabled)

import source_rc
