# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/report.ui'
#
# Created: Sat Aug 12 19:36:42 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(907, 575)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 8, 1, 1, 1)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 7, 0, 1, 2)
        self.baid_lbl = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baid_lbl.sizePolicy().hasHeightForWidth())
        self.baid_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(20)
        self.baid_lbl.setFont(font)
        self.baid_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.baid_lbl.setObjectName("baid_lbl")
        self.gridLayout_2.addWidget(self.baid_lbl, 5, 0, 1, 1)
        self.tottal_lbl = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(20)
        self.tottal_lbl.setFont(font)
        self.tottal_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.tottal_lbl.setObjectName("tottal_lbl")
        self.gridLayout_2.addWidget(self.tottal_lbl, 8, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 2, 0, 1, 2)
        self.widget_51 = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_51.sizePolicy().hasHeightForWidth())
        self.widget_51.setSizePolicy(sizePolicy)
        self.widget_51.setObjectName("widget_51")
        self.gridLayout_23 = QtGui.QGridLayout(self.widget_51)
        self.gridLayout_23.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.st_dt = QtGui.QDateTimeEdit(self.widget_51)
        self.st_dt.setCalendarPopup(True)
        self.st_dt.setObjectName("st_dt")
        self.gridLayout_23.addWidget(self.st_dt, 0, 3, 1, 1)
        self.label_93 = QtGui.QLabel(self.widget_51)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_93.sizePolicy().hasHeightForWidth())
        self.label_93.setSizePolicy(sizePolicy)
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.gridLayout_23.addWidget(self.label_93, 0, 2, 1, 1)
        self.label_92 = QtGui.QLabel(self.widget_51)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_92.sizePolicy().hasHeightForWidth())
        self.label_92.setSizePolicy(sizePolicy)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.gridLayout_23.addWidget(self.label_92, 0, 4, 1, 1)
        self.end_dt = QtGui.QDateTimeEdit(self.widget_51)
        self.end_dt.setCalendarPopup(True)
        self.end_dt.setObjectName("end_dt")
        self.gridLayout_23.addWidget(self.end_dt, 0, 1, 1, 1)
        self.widget_55 = QtGui.QWidget(self.widget_51)
        self.widget_55.setObjectName("widget_55")
        self.gridLayout_23.addWidget(self.widget_55, 0, 5, 1, 1)
        self.widget_54 = QtGui.QWidget(self.widget_51)
        self.widget_54.setObjectName("widget_54")
        self.gridLayout_23.addWidget(self.widget_54, 0, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.widget_51)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.print_btn = QtGui.QPushButton(self.widget_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/n/img/Printer Door Open Filled-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.print_btn.setIcon(icon)
        self.print_btn.setIconSize(QtCore.QSize(50, 50))
        self.print_btn.setFlat(True)
        self.print_btn.setObjectName("print_btn")
        self.horizontalLayout.addWidget(self.print_btn)
        self.all_btn = QtGui.QPushButton(self.widget_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/n/img/icons8-Select All-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.all_btn.setIcon(icon1)
        self.all_btn.setIconSize(QtCore.QSize(50, 50))
        self.all_btn.setFlat(True)
        self.all_btn.setObjectName("all_btn")
        self.horizontalLayout.addWidget(self.all_btn)
        self.search_btn = QtGui.QPushButton(self.widget_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/n/img/Search-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon2)
        self.search_btn.setIconSize(QtCore.QSize(50, 50))
        self.search_btn.setFlat(True)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.gridLayout_23.addWidget(self.widget_2, 1, 1, 1, 4)
        self.gridLayout_2.addWidget(self.widget_51, 1, 0, 1, 2)
        self.rest_lbl = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(20)
        self.rest_lbl.setFont(font)
        self.rest_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.rest_lbl.setObjectName("rest_lbl")
        self.gridLayout_2.addWidget(self.rest_lbl, 6, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 6, 1, 1, 1)
        self.all_lbl = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(20)
        self.all_lbl.setFont(font)
        self.all_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.all_lbl.setObjectName("all_lbl")
        self.gridLayout_2.addWidget(self.all_lbl, 4, 0, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(26)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 0, 0, 1, 2)
        self.label_134 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(20)
        self.label_134.setFont(font)
        self.label_134.setAlignment(QtCore.Qt.AlignCenter)
        self.label_134.setObjectName("label_134")
        self.gridLayout_2.addWidget(self.label_134, 5, 1, 1, 1)
        self.all_items = QtGui.QTableWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.all_items.sizePolicy().hasHeightForWidth())
        self.all_items.setSizePolicy(sizePolicy)
        self.all_items.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.all_items.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.all_items.setObjectName("all_items")
        self.all_items.setColumnCount(8)
        self.all_items.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.all_items.setHorizontalHeaderItem(7, item)
        self.gridLayout_2.addWidget(self.all_items, 3, 0, 1, 2)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "الاجمالى", None, QtGui.QApplication.UnicodeUTF8))
        self.baid_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tottal_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_93.setText(QtGui.QApplication.translate("Form", "الى", None, QtGui.QApplication.UnicodeUTF8))
        self.label_92.setText(QtGui.QApplication.translate("Form", "من", None, QtGui.QApplication.UnicodeUTF8))
        self.print_btn.setText(QtGui.QApplication.translate("Form", "طباعة", None, QtGui.QApplication.UnicodeUTF8))
        self.all_btn.setText(QtGui.QApplication.translate("Form", "كل العمليات", None, QtGui.QApplication.UnicodeUTF8))
        self.search_btn.setText(QtGui.QApplication.translate("Form", "بحث", None, QtGui.QApplication.UnicodeUTF8))
        self.rest_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "الباقى", None, QtGui.QApplication.UnicodeUTF8))
        self.all_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "المقرر دفعة", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("Form", "تقرير المالية المجمع", None, QtGui.QApplication.UnicodeUTF8))
        self.label_134.setText(QtGui.QApplication.translate("Form", "المدفوع", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "رقم الطالب", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "اسم الطالب", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "المجموعة", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "نوع الدفع", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "معاد الدفع", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Form", "المقرر دفعة", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Form", "المدفوع", None, QtGui.QApplication.UnicodeUTF8))
        self.all_items.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Form", "يوم الدفع", None, QtGui.QApplication.UnicodeUTF8))

import source_rc
