# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/st_report.ui'
#
# Created: Wed Feb 07 20:58:47 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(965, 537)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtGui.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtGui.QGridLayout(self.widget_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_7 = QtGui.QWidget(self.widget_4)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout.addWidget(self.widget_7, 1, 7, 1, 1)
        self.widget_6 = QtGui.QWidget(self.widget_4)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout.addWidget(self.widget_6, 1, 0, 1, 1)
        self.widget_8 = QtGui.QWidget(self.widget_4)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout.addWidget(self.widget_8, 1, 6, 1, 1)
        self.widget_12 = QtGui.QWidget(self.widget_4)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_12)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gp_name = QtGui.QComboBox(self.widget_12)
        self.gp_name.setObjectName("gp_name")
        self.horizontalLayout_4.addWidget(self.gp_name)
        self.gridLayout.addWidget(self.widget_12, 3, 2, 1, 4)
        self.widget_13 = QtGui.QWidget(self.widget_4)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_13)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.print_btn = QtGui.QPushButton(self.widget_13)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/n/img/Printer Door Open Filled-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.print_btn.setIcon(icon)
        self.print_btn.setIconSize(QtCore.QSize(30, 30))
        self.print_btn.setFlat(True)
        self.print_btn.setObjectName("print_btn")
        self.horizontalLayout_3.addWidget(self.print_btn)
        self.search_btn = QtGui.QPushButton(self.widget_13)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/n/img/Search-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon1)
        self.search_btn.setIconSize(QtCore.QSize(30, 30))
        self.search_btn.setFlat(True)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_3.addWidget(self.search_btn)
        self.gridLayout.addWidget(self.widget_13, 4, 2, 1, 4)
        self.st_search_edt = QtGui.QLineEdit(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.st_search_edt.sizePolicy().hasHeightForWidth())
        self.st_search_edt.setSizePolicy(sizePolicy)
        self.st_search_edt.setMinimumSize(QtCore.QSize(0, 40))
        self.st_search_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.st_search_edt.setObjectName("st_search_edt")
        self.gridLayout.addWidget(self.st_search_edt, 0, 2, 1, 4)
        self.label_2 = QtGui.QLabel(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 3, 1, 1)
        self.end_dt = QtGui.QDateEdit(self.widget_4)
        self.end_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.end_dt.setCalendarPopup(True)
        self.end_dt.setObjectName("end_dt")
        self.gridLayout.addWidget(self.end_dt, 1, 2, 1, 1)
        self.st_dt = QtGui.QDateEdit(self.widget_4)
        self.st_dt.setAlignment(QtCore.Qt.AlignCenter)
        self.st_dt.setCalendarPopup(True)
        self.st_dt.setObjectName("st_dt")
        self.gridLayout.addWidget(self.st_dt, 1, 4, 1, 1)
        self.label_15 = QtGui.QLabel(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 2, 1, 4)
        self.widget_9 = QtGui.QWidget(self.widget_4)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout.addWidget(self.widget_9, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.widget_4)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_16 = QtGui.QWidget(self.widget)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_5 = QtGui.QGridLayout(self.widget_16)
        self.gridLayout_5.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.report_table = QtGui.QTableWidget(self.widget_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.report_table.sizePolicy().hasHeightForWidth())
        self.report_table.setSizePolicy(sizePolicy)
        self.report_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.report_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.report_table.setObjectName("report_table")
        self.report_table.setColumnCount(3)
        self.report_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.report_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.report_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.report_table.setHorizontalHeaderItem(2, item)
        self.gridLayout_5.addWidget(self.report_table, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 1, 1, 1)
        self.widget_5 = QtGui.QWidget(self.widget_16)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_5.addWidget(self.widget_5, 3, 0, 1, 1)
        self.widget_3 = QtGui.QWidget(self.widget_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet(".QLabel\n"
"{\n"
"background:#000;\n"
"color:#fff;\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 10, 1, 1, 1)
        self.ph_lbl = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ph_lbl.sizePolicy().hasHeightForWidth())
        self.ph_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.ph_lbl.setFont(font)
        self.ph_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ph_lbl.setObjectName("ph_lbl")
        self.gridLayout_2.addWidget(self.ph_lbl, 8, 0, 1, 1)
        self.fph_lbl = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fph_lbl.sizePolicy().hasHeightForWidth())
        self.fph_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.fph_lbl.setFont(font)
        self.fph_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fph_lbl.setObjectName("fph_lbl")
        self.gridLayout_2.addWidget(self.fph_lbl, 9, 0, 1, 1)
        self.details_lbl = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.details_lbl.sizePolicy().hasHeightForWidth())
        self.details_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.details_lbl.setFont(font)
        self.details_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.details_lbl.setObjectName("details_lbl")
        self.gridLayout_2.addWidget(self.details_lbl, 11, 0, 1, 1)
        self.mail_lbl = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mail_lbl.sizePolicy().hasHeightForWidth())
        self.mail_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.mail_lbl.setFont(font)
        self.mail_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.mail_lbl.setObjectName("mail_lbl")
        self.gridLayout_2.addWidget(self.mail_lbl, 10, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 9, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 11, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 8, 1, 1, 1)
        self.school_lbl = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.school_lbl.sizePolicy().hasHeightForWidth())
        self.school_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.school_lbl.setFont(font)
        self.school_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.school_lbl.setObjectName("school_lbl")
        self.gridLayout_2.addWidget(self.school_lbl, 4, 0, 1, 1)
        self.name_lbl = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_lbl.sizePolicy().hasHeightForWidth())
        self.name_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.name_lbl.setFont(font)
        self.name_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.name_lbl.setObjectName("name_lbl")
        self.gridLayout_2.addWidget(self.name_lbl, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 1, 1, 1)
        self.bc_label = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bc_label.sizePolicy().hasHeightForWidth())
        self.bc_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.bc_label.setFont(font)
        self.bc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bc_label.setObjectName("bc_label")
        self.gridLayout_2.addWidget(self.bc_label, 1, 0, 1, 1)
        self.add_lbl = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_lbl.sizePolicy().hasHeightForWidth())
        self.add_lbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("AlArabiya")
        font.setPointSize(12)
        self.add_lbl.setFont(font)
        self.add_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.add_lbl.setObjectName("add_lbl")
        self.gridLayout_2.addWidget(self.add_lbl, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_3, 1, 1, 1, 1)
        self.ratio_lbl = QtGui.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setFamily("Alarabiya Font")
        font.setPointSize(26)
        self.ratio_lbl.setFont(font)
        self.ratio_lbl.setStyleSheet("background:#000;\n"
"color:#fff;")
        self.ratio_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ratio_lbl.setObjectName("ratio_lbl")
        self.gridLayout_5.addWidget(self.ratio_lbl, 2, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.widget_16)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "تقرير مفصل عن الطالب", None, QtGui.QApplication.UnicodeUTF8))
        self.print_btn.setText(QtGui.QApplication.translate("Form", "طباعة", None, QtGui.QApplication.UnicodeUTF8))
        self.search_btn.setText(QtGui.QApplication.translate("Form", "بحث", None, QtGui.QApplication.UnicodeUTF8))
        self.st_search_edt.setPlaceholderText(QtGui.QApplication.translate("Form", "الباركود - الهاتف - الاسم", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "من", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "الى", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "المجموعة", None, QtGui.QApplication.UnicodeUTF8))
        self.report_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "النوع", None, QtGui.QApplication.UnicodeUTF8))
        self.report_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "التقييم", None, QtGui.QApplication.UnicodeUTF8))
        self.report_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "تفاصيل", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "تقرير الطالب", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "بيانات الطالب", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "البريد الالكترونى", None, QtGui.QApplication.UnicodeUTF8))
        self.ph_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.fph_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.details_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.mail_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "هاتف ولى الامر", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "التفاصيل", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "الهاتف", None, QtGui.QApplication.UnicodeUTF8))
        self.school_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.name_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "الباركود", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "الاسم", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "العنوان", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "المدرسة", None, QtGui.QApplication.UnicodeUTF8))
        self.bc_label.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.add_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.ratio_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))

import source_rc
