# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/students_info.ui'
#
# Created: Tue Jun 26 14:14:20 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(671, 558)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtGui.QWidget(Form)
        self.widget_4.setStyleSheet("background-color: #05B963;\n"
"color:#07020D;\n"
"padding:8px;\n"
"border:0px;")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groups_btn = QtGui.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Alarabiya Font")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.groups_btn.setFont(font)
        self.groups_btn.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/n/img/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.groups_btn.setIcon(icon)
        self.groups_btn.setIconSize(QtCore.QSize(30, 30))
        self.groups_btn.setFlat(False)
        self.groups_btn.setObjectName("groups_btn")
        self.horizontalLayout.addWidget(self.groups_btn)
        self.attend_btn = QtGui.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Alarabiya Font")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.attend_btn.setFont(font)
        self.attend_btn.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/n/img/Future-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.attend_btn.setIcon(icon1)
        self.attend_btn.setIconSize(QtCore.QSize(30, 30))
        self.attend_btn.setFlat(False)
        self.attend_btn.setObjectName("attend_btn")
        self.horizontalLayout.addWidget(self.attend_btn)
        self.mony_btn = QtGui.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Alarabiya Font")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.mony_btn.setFont(font)
        self.mony_btn.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/n/img/Money-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mony_btn.setIcon(icon2)
        self.mony_btn.setIconSize(QtCore.QSize(30, 30))
        self.mony_btn.setFlat(False)
        self.mony_btn.setObjectName("mony_btn")
        self.horizontalLayout.addWidget(self.mony_btn)
        self.verticalLayout.addWidget(self.widget_4)
        self.stackedWidget = QtGui.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_7 = QtGui.QWidget(self.page_2)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_7)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_st_course = QtGui.QTableWidget(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_st_course.sizePolicy().hasHeightForWidth())
        self.table_st_course.setSizePolicy(sizePolicy)
        self.table_st_course.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.table_st_course.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_st_course.setObjectName("table_st_course")
        self.table_st_course.setColumnCount(5)
        self.table_st_course.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_st_course.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_st_course.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_st_course.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_st_course.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_st_course.setHorizontalHeaderItem(4, item)
        self.gridLayout_3.addWidget(self.table_st_course, 3, 0, 1, 1)
        self.add_group_btn = QtGui.QPushButton(self.widget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_group_btn.sizePolicy().hasHeightForWidth())
        self.add_group_btn.setSizePolicy(sizePolicy)
        self.add_group_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/n/img/Plus-500.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_group_btn.setIcon(icon3)
        self.add_group_btn.setIconSize(QtCore.QSize(25, 25))
        self.add_group_btn.setFlat(True)
        self.add_group_btn.setObjectName("add_group_btn")
        self.gridLayout_3.addWidget(self.add_group_btn, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_7)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_18 = QtGui.QWidget(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_18)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_19 = QtGui.QWidget(self.widget_18)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_7.addWidget(self.widget_19)
        self.widget_20 = QtGui.QWidget(self.widget_18)
        self.widget_20.setObjectName("widget_20")
        self.gridLayout_5 = QtGui.QGridLayout(self.widget_20)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtGui.QLabel(self.widget_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 1, 1, 1)
        self.widget_24 = QtGui.QWidget(self.widget_20)
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_24)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.att_print_btn = QtGui.QPushButton(self.widget_24)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/n/img/Printer Door Open Filled-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.att_print_btn.setIcon(icon4)
        self.att_print_btn.setIconSize(QtCore.QSize(30, 30))
        self.att_print_btn.setFlat(True)
        self.att_print_btn.setObjectName("att_print_btn")
        self.horizontalLayout_9.addWidget(self.att_print_btn)
        self.att_search_btn = QtGui.QPushButton(self.widget_24)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/n/img/Search-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.att_search_btn.setIcon(icon5)
        self.att_search_btn.setIconSize(QtCore.QSize(30, 30))
        self.att_search_btn.setFlat(True)
        self.att_search_btn.setObjectName("att_search_btn")
        self.horizontalLayout_9.addWidget(self.att_search_btn)
        self.gridLayout_5.addWidget(self.widget_24, 3, 0, 1, 3)
        self.label_9 = QtGui.QLabel(self.widget_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 2, 1, 1)
        self.course_cmb = QtGui.QComboBox(self.widget_20)
        self.course_cmb.setObjectName("course_cmb")
        self.gridLayout_5.addWidget(self.course_cmb, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget_20)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 2, 1, 1, 1)
        self.month_cmb = QtGui.QComboBox(self.widget_20)
        self.month_cmb.setObjectName("month_cmb")
        self.gridLayout_5.addWidget(self.month_cmb, 2, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.widget_20)
        self.widget_21 = QtGui.QWidget(self.widget_18)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_7.addWidget(self.widget_21)
        self.verticalLayout_6.addWidget(self.widget_18)
        self.widget_17 = QtGui.QWidget(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.widget_17.sizePolicy().hasHeightForWidth())
        self.widget_17.setSizePolicy(sizePolicy)
        self.widget_17.setObjectName("widget_17")
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_17)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.att_table = QtGui.QTableWidget(self.widget_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.att_table.sizePolicy().hasHeightForWidth())
        self.att_table.setSizePolicy(sizePolicy)
        self.att_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.att_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.att_table.setObjectName("att_table")
        self.att_table.setColumnCount(2)
        self.att_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.att_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.att_table.setHorizontalHeaderItem(1, item)
        self.gridLayout_4.addWidget(self.att_table, 0, 1, 1, 1)
        self.widget_22 = QtGui.QWidget(self.widget_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_22.sizePolicy().hasHeightForWidth())
        self.widget_22.setSizePolicy(sizePolicy)
        self.widget_22.setStyleSheet(".QLabel\n"
"{\n"
"background:#000;\n"
"color:#fff;\n"
"}\n"
"")
        self.widget_22.setObjectName("widget_22")
        self.gridLayout_6 = QtGui.QGridLayout(self.widget_22)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(2)
        self.gridLayout_6.setVerticalSpacing(1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_14 = QtGui.QLabel(self.widget_22)
        self.label_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 1, 1, 1, 1)
        self.attend = QtGui.QLabel(self.widget_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attend.sizePolicy().hasHeightForWidth())
        self.attend.setSizePolicy(sizePolicy)
        self.attend.setAlignment(QtCore.Qt.AlignCenter)
        self.attend.setObjectName("attend")
        self.gridLayout_6.addWidget(self.attend, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget_22)
        self.label_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 2, 1, 1, 1)
        self.absent = QtGui.QLabel(self.widget_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.absent.sizePolicy().hasHeightForWidth())
        self.absent.setSizePolicy(sizePolicy)
        self.absent.setAlignment(QtCore.Qt.AlignCenter)
        self.absent.setObjectName("absent")
        self.gridLayout_6.addWidget(self.absent, 1, 0, 1, 1)
        self.ratio = QtGui.QLabel(self.widget_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ratio.sizePolicy().hasHeightForWidth())
        self.ratio.setSizePolicy(sizePolicy)
        self.ratio.setAlignment(QtCore.Qt.AlignCenter)
        self.ratio.setObjectName("ratio")
        self.gridLayout_6.addWidget(self.ratio, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_22, 1, 0, 1, 3)
        self.verticalLayout_6.addWidget(self.widget_17)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_26 = QtGui.QWidget(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_26.sizePolicy().hasHeightForWidth())
        self.widget_26.setSizePolicy(sizePolicy)
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_26)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_27 = QtGui.QWidget(self.widget_26)
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_8.addWidget(self.widget_27)
        self.widget_28 = QtGui.QWidget(self.widget_26)
        self.widget_28.setObjectName("widget_28")
        self.gridLayout_8 = QtGui.QGridLayout(self.widget_28)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.course_mn_cmb = QtGui.QComboBox(self.widget_28)
        self.course_mn_cmb.setObjectName("course_mn_cmb")
        self.gridLayout_8.addWidget(self.course_mn_cmb, 1, 0, 1, 1)
        self.widget_29 = QtGui.QWidget(self.widget_28)
        self.widget_29.setObjectName("widget_29")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_29)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.mn_print_btn = QtGui.QPushButton(self.widget_29)
        self.mn_print_btn.setIcon(icon4)
        self.mn_print_btn.setIconSize(QtCore.QSize(30, 30))
        self.mn_print_btn.setFlat(True)
        self.mn_print_btn.setObjectName("mn_print_btn")
        self.horizontalLayout_10.addWidget(self.mn_print_btn)
        self.mn_search_btn = QtGui.QPushButton(self.widget_29)
        self.mn_search_btn.setIcon(icon5)
        self.mn_search_btn.setIconSize(QtCore.QSize(30, 30))
        self.mn_search_btn.setFlat(True)
        self.mn_search_btn.setObjectName("mn_search_btn")
        self.horizontalLayout_10.addWidget(self.mn_search_btn)
        self.gridLayout_8.addWidget(self.widget_29, 2, 0, 1, 3)
        self.label_18 = QtGui.QLabel(self.widget_28)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.widget_28)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 1, 2, 1, 1)
        self.horizontalLayout_8.addWidget(self.widget_28)
        self.widget_30 = QtGui.QWidget(self.widget_26)
        self.widget_30.setObjectName("widget_30")
        self.horizontalLayout_8.addWidget(self.widget_30)
        self.verticalLayout_7.addWidget(self.widget_26)
        self.widget_23 = QtGui.QWidget(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.widget_23.sizePolicy().hasHeightForWidth())
        self.widget_23.setSizePolicy(sizePolicy)
        self.widget_23.setObjectName("widget_23")
        self.gridLayout_9 = QtGui.QGridLayout(self.widget_23)
        self.gridLayout_9.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.mn_table = QtGui.QTableWidget(self.widget_23)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.mn_table.sizePolicy().hasHeightForWidth())
        self.mn_table.setSizePolicy(sizePolicy)
        self.mn_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.mn_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.mn_table.setObjectName("mn_table")
        self.mn_table.setColumnCount(5)
        self.mn_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mn_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mn_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mn_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.mn_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.mn_table.setHorizontalHeaderItem(4, item)
        self.gridLayout_9.addWidget(self.mn_table, 0, 1, 1, 1)
        self.widget_25 = QtGui.QWidget(self.widget_23)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_25.sizePolicy().hasHeightForWidth())
        self.widget_25.setSizePolicy(sizePolicy)
        self.widget_25.setStyleSheet(".QLabel\n"
"{\n"
"background:#000;\n"
"color:#fff;\n"
"}\n"
"")
        self.widget_25.setObjectName("widget_25")
        self.gridLayout_7 = QtGui.QGridLayout(self.widget_25)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setHorizontalSpacing(2)
        self.gridLayout_7.setVerticalSpacing(1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_15 = QtGui.QLabel(self.widget_25)
        self.label_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 1, 1, 1, 1)
        self.tottal_mony = QtGui.QLabel(self.widget_25)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tottal_mony.sizePolicy().hasHeightForWidth())
        self.tottal_mony.setSizePolicy(sizePolicy)
        self.tottal_mony.setAlignment(QtCore.Qt.AlignCenter)
        self.tottal_mony.setObjectName("tottal_mony")
        self.gridLayout_7.addWidget(self.tottal_mony, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget_25)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.widget_25)
        self.label_17.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 2, 1, 1, 1)
        self.baid_mony = QtGui.QLabel(self.widget_25)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baid_mony.sizePolicy().hasHeightForWidth())
        self.baid_mony.setSizePolicy(sizePolicy)
        self.baid_mony.setAlignment(QtCore.Qt.AlignCenter)
        self.baid_mony.setObjectName("baid_mony")
        self.gridLayout_7.addWidget(self.baid_mony, 1, 0, 1, 1)
        self.rest_mony = QtGui.QLabel(self.widget_25)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rest_mony.sizePolicy().hasHeightForWidth())
        self.rest_mony.setSizePolicy(sizePolicy)
        self.rest_mony.setAlignment(QtCore.Qt.AlignCenter)
        self.rest_mony.setObjectName("rest_mony")
        self.gridLayout_7.addWidget(self.rest_mony, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.widget_25, 1, 0, 1, 3)
        self.verticalLayout_7.addWidget(self.widget_23)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groups_btn.setText(QtGui.QApplication.translate("Form", "المجموعات", None, QtGui.QApplication.UnicodeUTF8))
        self.attend_btn.setText(QtGui.QApplication.translate("Form", "الحضور", None, QtGui.QApplication.UnicodeUTF8))
        self.mony_btn.setText(QtGui.QApplication.translate("Form", "تقرير المالية", None, QtGui.QApplication.UnicodeUTF8))
        self.table_st_course.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "اسم المجموعة", None, QtGui.QApplication.UnicodeUTF8))
        self.table_st_course.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "عدد ساعات المجموعة", None, QtGui.QApplication.UnicodeUTF8))
        self.table_st_course.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "عدد الايام", None, QtGui.QApplication.UnicodeUTF8))
        self.table_st_course.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "حذف", None, QtGui.QApplication.UnicodeUTF8))
        self.table_st_course.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "تبديل", None, QtGui.QApplication.UnicodeUTF8))
        self.add_group_btn.setText(QtGui.QApplication.translate("Form", "اضافة مجموعة", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "المجموعة", None, QtGui.QApplication.UnicodeUTF8))
        self.att_print_btn.setText(QtGui.QApplication.translate("Form", "طباعة", None, QtGui.QApplication.UnicodeUTF8))
        self.att_search_btn.setText(QtGui.QApplication.translate("Form", "بحث", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "الشهر", None, QtGui.QApplication.UnicodeUTF8))
        self.att_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "اليوم", None, QtGui.QApplication.UnicodeUTF8))
        self.att_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "الحالة", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "عدد ايام الغياب", None, QtGui.QApplication.UnicodeUTF8))
        self.attend.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "عدد ايام الحضور", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "النسبة", None, QtGui.QApplication.UnicodeUTF8))
        self.absent.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.ratio.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.mn_print_btn.setText(QtGui.QApplication.translate("Form", "طباعة", None, QtGui.QApplication.UnicodeUTF8))
        self.mn_search_btn.setText(QtGui.QApplication.translate("Form", "بحث", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "المجموعة", None, QtGui.QApplication.UnicodeUTF8))
        self.mn_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "المعاد", None, QtGui.QApplication.UnicodeUTF8))
        self.mn_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "المقرر دفعة", None, QtGui.QApplication.UnicodeUTF8))
        self.mn_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "المدفوع", None, QtGui.QApplication.UnicodeUTF8))
        self.mn_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "الباقى", None, QtGui.QApplication.UnicodeUTF8))
        self.mn_table.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "دفع", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "المدفوع", None, QtGui.QApplication.UnicodeUTF8))
        self.tottal_mony.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "المقرر دفعة", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "الباقى", None, QtGui.QApplication.UnicodeUTF8))
        self.baid_mony.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.rest_mony.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))

import source_rc
