# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/students_dw.ui'
#
# Created: Mon Jun 18 20:28:56 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(328, 421)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtGui.QWidget(Form)
        self.widget_3.setStyleSheet(".QWidget { background: #44D9E6; }")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtGui.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.nm_edt = QtGui.QLineEdit(self.widget_3)
        self.nm_edt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.nm_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.nm_edt.setObjectName("nm_edt")
        self.gridLayout.addWidget(self.nm_edt, 2, 0, 1, 2)
        self.label = QtGui.QLabel(self.widget_3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1)
        self.barcode_get_btn = QtGui.QPushButton(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barcode_get_btn.sizePolicy().hasHeightForWidth())
        self.barcode_get_btn.setSizePolicy(sizePolicy)
        self.barcode_get_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/n/img/Recycling-104.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.barcode_get_btn.setIcon(icon)
        self.barcode_get_btn.setObjectName("barcode_get_btn")
        self.gridLayout.addWidget(self.barcode_get_btn, 1, 0, 1, 1)
        self.bc_edt = QtGui.QLineEdit(self.widget_3)
        self.bc_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.bc_edt.setObjectName("bc_edt")
        self.gridLayout.addWidget(self.bc_edt, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget_3)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget_3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1)
        self.mail_edt = QtGui.QLineEdit(self.widget_3)
        self.mail_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.mail_edt.setObjectName("mail_edt")
        self.gridLayout.addWidget(self.mail_edt, 6, 0, 1, 2)
        self.ph_edt = QtGui.QLineEdit(self.widget_3)
        self.ph_edt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ph_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.ph_edt.setObjectName("ph_edt")
        self.gridLayout.addWidget(self.ph_edt, 4, 0, 1, 2)
        self.school_edt = QtGui.QLineEdit(self.widget_3)
        self.school_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.school_edt.setObjectName("school_edt")
        self.gridLayout.addWidget(self.school_edt, 3, 0, 1, 2)
        self.fphon_edt = QtGui.QLineEdit(self.widget_3)
        self.fphon_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.fphon_edt.setObjectName("fphon_edt")
        self.gridLayout.addWidget(self.fphon_edt, 5, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.widget_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 2, 1, 1)
        self.address_edt = QtGui.QLineEdit(self.widget_3)
        self.address_edt.setAlignment(QtCore.Qt.AlignCenter)
        self.address_edt.setObjectName("address_edt")
        self.gridLayout.addWidget(self.address_edt, 7, 0, 1, 2)
        self.label_8 = QtGui.QLabel(self.widget_3)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 2, 1, 1)
        self.details_edt = QtGui.QTextEdit(self.widget_3)
        self.details_edt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.details_edt.setObjectName("details_edt")
        self.gridLayout.addWidget(self.details_edt, 8, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.widget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget_3)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 8, 2, 1, 1)
        self.widget = QtGui.QWidget(self.widget_3)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delete_btn = QtGui.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/n/img/Delete-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_btn.setIcon(icon1)
        self.delete_btn.setIconSize(QtCore.QSize(30, 30))
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)
        self.edite_btn = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edite_btn.sizePolicy().hasHeightForWidth())
        self.edite_btn.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/n/img/edit-document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edite_btn.setIcon(icon2)
        self.edite_btn.setIconSize(QtCore.QSize(30, 30))
        self.edite_btn.setObjectName("edite_btn")
        self.horizontalLayout.addWidget(self.edite_btn)
        self.reports_btn = QtGui.QPushButton(self.widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/n/img/line-chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reports_btn.setIcon(icon3)
        self.reports_btn.setIconSize(QtCore.QSize(30, 30))
        self.reports_btn.setObjectName("reports_btn")
        self.horizontalLayout.addWidget(self.reports_btn)
        self.add_btn = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_btn.sizePolicy().hasHeightForWidth())
        self.add_btn.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/n/img/Plus-500.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn.setIcon(icon4)
        self.add_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.gridLayout.addWidget(self.widget, 9, 0, 1, 3)
        self.widget_2 = QtGui.QWidget(self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bc_lbl = QtGui.QLabel(self.widget_2)
        self.bc_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.bc_lbl.setObjectName("bc_lbl")
        self.horizontalLayout_2.addWidget(self.bc_lbl)
        self.ph_lbl = QtGui.QLabel(self.widget_2)
        self.ph_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ph_lbl.setObjectName("ph_lbl")
        self.horizontalLayout_2.addWidget(self.ph_lbl)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.bc_edt, self.nm_edt)
        Form.setTabOrder(self.nm_edt, self.school_edt)
        Form.setTabOrder(self.school_edt, self.ph_edt)
        Form.setTabOrder(self.ph_edt, self.fphon_edt)
        Form.setTabOrder(self.fphon_edt, self.mail_edt)
        Form.setTabOrder(self.mail_edt, self.address_edt)
        Form.setTabOrder(self.address_edt, self.details_edt)
        Form.setTabOrder(self.details_edt, self.add_btn)
        Form.setTabOrder(self.add_btn, self.edite_btn)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "الاسم", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "هاتف ولى الامر", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "المدرسة", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "البريد الاكترونى", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "الهاتف", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "العنوان", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "الباركود", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "تفاصيل", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_btn.setText(QtGui.QApplication.translate("Form", "حذف", None, QtGui.QApplication.UnicodeUTF8))
        self.edite_btn.setText(QtGui.QApplication.translate("Form", "تعديل", None, QtGui.QApplication.UnicodeUTF8))
        self.reports_btn.setText(QtGui.QApplication.translate("Form", "تقارير", None, QtGui.QApplication.UnicodeUTF8))
        self.add_btn.setText(QtGui.QApplication.translate("Form", "اضافة", None, QtGui.QApplication.UnicodeUTF8))
        self.bc_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.ph_lbl.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))

import source_rc
import source_rc
