# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/user_widget.ui'
#
# Created: Sun Jul 30 13:33:54 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(324, 449)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tot_w_2 = QtGui.QWidget(Form)
        self.tot_w_2.setStyleSheet(".QWidget{\n"
"background:#44D9E6;\n"
"}\n"
".QLabel\n"
"{\n"
"color:#000;\n"
"}\n"
".QPushButton{color:#000;\n"
"}")
        self.tot_w_2.setObjectName("tot_w_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.tot_w_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtGui.QWidget(self.tot_w_2)
        self.widget.setObjectName("widget")
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_4 = QtGui.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.user = QtGui.QRadioButton(self.widget_4)
        self.user.setObjectName("user")
        self.horizontalLayout_4.addWidget(self.user)
        self.manage = QtGui.QRadioButton(self.widget_4)
        self.manage.setObjectName("manage")
        self.horizontalLayout_4.addWidget(self.manage)
        self.gridLayout.addWidget(self.widget_4, 4, 0, 1, 2)
        self.widget_12 = QtGui.QWidget(self.widget)
        self.widget_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_12)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_save = QtGui.QPushButton(self.widget_12)
        self.add_save.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.add_save.setFont(font)
        self.add_save.setIconSize(QtCore.QSize(30, 30))
        self.add_save.setObjectName("add_save")
        self.horizontalLayout.addWidget(self.add_save)
        self.cancel_save = QtGui.QPushButton(self.widget_12)
        self.cancel_save.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.cancel_save.setFont(font)
        self.cancel_save.setIconSize(QtCore.QSize(30, 30))
        self.cancel_save.setObjectName("cancel_save")
        self.horizontalLayout.addWidget(self.cancel_save)
        self.gridLayout.addWidget(self.widget_12, 10, 0, 1, 2)
        self.line_8 = QtGui.QFrame(self.widget)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 5, 0, 1, 2)
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.alerm = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alerm.sizePolicy().hasHeightForWidth())
        self.alerm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.alerm.setFont(font)
        self.alerm.setStyleSheet("color:#fff;")
        self.alerm.setText("")
        self.alerm.setAlignment(QtCore.Qt.AlignCenter)
        self.alerm.setObjectName("alerm")
        self.horizontalLayout_2.addWidget(self.alerm)
        self.gridLayout.addWidget(self.widget_2, 6, 0, 1, 2)
        self.widget_5 = QtGui.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.u_name = QtGui.QLineEdit(self.widget_5)
        self.u_name.setAlignment(QtCore.Qt.AlignCenter)
        self.u_name.setObjectName("u_name")
        self.horizontalLayout_5.addWidget(self.u_name)
        self.label_70 = QtGui.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_70.setFont(font)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_5.addWidget(self.label_70)
        self.gridLayout.addWidget(self.widget_5, 2, 0, 1, 1)
        self.widget_3 = QtGui.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.name = QtGui.QLineEdit(self.widget_3)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.horizontalLayout_3.addWidget(self.name)
        self.label_69 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_69.setFont(font)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_3.addWidget(self.label_69)
        self.gridLayout.addWidget(self.widget_3, 1, 0, 1, 1)
        self.widget_6 = QtGui.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.passwd = QtGui.QLineEdit(self.widget_6)
        self.passwd.setAlignment(QtCore.Qt.AlignCenter)
        self.passwd.setObjectName("passwd")
        self.horizontalLayout_8.addWidget(self.passwd)
        self.label_73 = QtGui.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_73.setFont(font)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_8.addWidget(self.label_73)
        self.gridLayout.addWidget(self.widget_6, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 1, 1, 2)
        self.verticalLayout.addWidget(self.tot_w_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.user.setText(QtGui.QApplication.translate("Form", "مستخدم", None, QtGui.QApplication.UnicodeUTF8))
        self.manage.setText(QtGui.QApplication.translate("Form", "مدير", None, QtGui.QApplication.UnicodeUTF8))
        self.add_save.setText(QtGui.QApplication.translate("Form", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_save.setText(QtGui.QApplication.translate("Form", "cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("Form", "اسم الدخول", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("Form", "الاسم كامل", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("Form", "الرقم السرى", None, QtGui.QApplication.UnicodeUTF8))

import source_rc
