# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/users.ui'
#
# Created: Thu Mar 16 09:09:39 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(621, 430)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_14 = QtGui.QWidget(Form)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_14)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_159 = QtGui.QWidget(self.widget_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_159.sizePolicy().hasHeightForWidth())
        self.widget_159.setSizePolicy(sizePolicy)
        self.widget_159.setObjectName("widget_159")
        self.gridLayout_32 = QtGui.QGridLayout(self.widget_159)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.udelet = QtGui.QPushButton(self.widget_159)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.udelet.sizePolicy().hasHeightForWidth())
        self.udelet.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.udelet.setFont(font)
        self.udelet.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/n/img/Delete-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.udelet.setIcon(icon)
        self.udelet.setIconSize(QtCore.QSize(50, 50))
        self.udelet.setFlat(True)
        self.udelet.setObjectName("udelet")
        self.gridLayout_32.addWidget(self.udelet, 1, 1, 1, 1)
        self.uedit = QtGui.QPushButton(self.widget_159)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.uedit.sizePolicy().hasHeightForWidth())
        self.uedit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.uedit.setFont(font)
        self.uedit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/n/img/Save-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uedit.setIcon(icon1)
        self.uedit.setIconSize(QtCore.QSize(50, 50))
        self.uedit.setFlat(True)
        self.uedit.setObjectName("uedit")
        self.gridLayout_32.addWidget(self.uedit, 1, 2, 1, 1)
        self.utable = QtGui.QTableWidget(self.widget_159)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.utable.sizePolicy().hasHeightForWidth())
        self.utable.setSizePolicy(sizePolicy)
        self.utable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.utable.setObjectName("utable")
        self.utable.setColumnCount(5)
        self.utable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.utable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.utable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.utable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.utable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.utable.setHorizontalHeaderItem(4, item)
        self.gridLayout_32.addWidget(self.utable, 0, 1, 1, 2)
        self.horizontalLayout.addWidget(self.widget_159)
        self.widget_155 = QtGui.QWidget(self.widget_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_155.sizePolicy().hasHeightForWidth())
        self.widget_155.setSizePolicy(sizePolicy)
        self.widget_155.setStyleSheet("")
        self.widget_155.setObjectName("widget_155")
        self.verticalLayout_64 = QtGui.QVBoxLayout(self.widget_155)
        self.verticalLayout_64.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.widget_156 = QtGui.QWidget(self.widget_155)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.widget_156.sizePolicy().hasHeightForWidth())
        self.widget_156.setSizePolicy(sizePolicy)
        self.widget_156.setObjectName("widget_156")
        self.verticalLayout_45 = QtGui.QVBoxLayout(self.widget_156)
        self.verticalLayout_45.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.widget_16 = QtGui.QWidget(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_45.addWidget(self.widget_16)
        self.ufname = QtGui.QLineEdit(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ufname.sizePolicy().hasHeightForWidth())
        self.ufname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.ufname.setFont(font)
        self.ufname.setAlignment(QtCore.Qt.AlignCenter)
        self.ufname.setObjectName("ufname")
        self.verticalLayout_45.addWidget(self.ufname)
        self.uname = QtGui.QLineEdit(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uname.sizePolicy().hasHeightForWidth())
        self.uname.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.uname.setFont(font)
        self.uname.setAlignment(QtCore.Qt.AlignCenter)
        self.uname.setObjectName("uname")
        self.verticalLayout_45.addWidget(self.uname)
        self.upass = QtGui.QLineEdit(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upass.sizePolicy().hasHeightForWidth())
        self.upass.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.upass.setFont(font)
        self.upass.setAlignment(QtCore.Qt.AlignCenter)
        self.upass.setObjectName("upass")
        self.verticalLayout_45.addWidget(self.upass)
        self.widget = QtGui.QWidget(self.widget_156)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.uadminradio = QtGui.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.uadminradio.setFont(font)
        self.uadminradio.setMouseTracking(True)
        self.uadminradio.setStyleSheet("")
        self.uadminradio.setChecked(True)
        self.uadminradio.setObjectName("uadminradio")
        self.horizontalLayout_30.addWidget(self.uadminradio)
        self.userradio = QtGui.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.userradio.setFont(font)
        self.userradio.setChecked(False)
        self.userradio.setObjectName("userradio")
        self.horizontalLayout_30.addWidget(self.userradio)
        self.verticalLayout_45.addWidget(self.widget)
        self.verticalLayout_64.addWidget(self.widget_156)
        self.widget_157 = QtGui.QWidget(self.widget_155)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_157.sizePolicy().hasHeightForWidth())
        self.widget_157.setSizePolicy(sizePolicy)
        self.widget_157.setObjectName("widget_157")
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.widget_157)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.uadd = QtGui.QPushButton(self.widget_157)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uadd.sizePolicy().hasHeightForWidth())
        self.uadd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.uadd.setFont(font)
        self.uadd.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/n/img/Plus-500.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uadd.setIcon(icon2)
        self.uadd.setIconSize(QtCore.QSize(50, 50))
        self.uadd.setFlat(True)
        self.uadd.setObjectName("uadd")
        self.horizontalLayout_31.addWidget(self.uadd)
        self.verticalLayout_64.addWidget(self.widget_157)
        self.widget_15 = QtGui.QWidget(self.widget_155)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_64.addWidget(self.widget_15)
        self.horizontalLayout.addWidget(self.widget_155)
        self.verticalLayout.addWidget(self.widget_14)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.utable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "الرقم", None, QtGui.QApplication.UnicodeUTF8))
        self.utable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "اﻻسم", None, QtGui.QApplication.UnicodeUTF8))
        self.utable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "اسم الدخول", None, QtGui.QApplication.UnicodeUTF8))
        self.utable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "الرقم السرى", None, QtGui.QApplication.UnicodeUTF8))
        self.utable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Form", "النوع", None, QtGui.QApplication.UnicodeUTF8))
        self.ufname.setPlaceholderText(QtGui.QApplication.translate("Form", "الاسم كامل", None, QtGui.QApplication.UnicodeUTF8))
        self.uname.setPlaceholderText(QtGui.QApplication.translate("Form", "اسم الدخول", None, QtGui.QApplication.UnicodeUTF8))
        self.upass.setPlaceholderText(QtGui.QApplication.translate("Form", "الرقم السرى", None, QtGui.QApplication.UnicodeUTF8))
        self.uadminradio.setText(QtGui.QApplication.translate("Form", "مدير", None, QtGui.QApplication.UnicodeUTF8))
        self.userradio.setText(QtGui.QApplication.translate("Form", "مستخدم", None, QtGui.QApplication.UnicodeUTF8))

import source_rc
